import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';

/**
 * API Gateway + Lambda example stack
 *
 * Demonstrates:
 * - REST API Gateway creation via Cloud Control API
 * - Lambda function with inline code (no asset publishing needed)
 * - Lambda integration with API Gateway
 * - Multiple resource types in one stack (API Gateway, Lambda, IAM)
 * - CfnOutput resolution with Fn::Join for API URL
 * - CORS preflight OPTIONS auto-generated by `defaultCorsPreflightOptions`,
 *   which emits AWS::ApiGateway::Method resources carrying both
 *   `Integration.IntegrationResponses` and `MethodResponses`. The
 *   `MethodResponse` for each statusCode MUST be created before the
 *   matching `IntegrationResponse`, otherwise AWS rejects with
 *   "Invalid mapping expression specified: ... [No method response
 *    exists for method.]" (pre-PR bug; regression-covered here).
 *
 * - Stage config props backfilled for issue #609: `tracingEnabled` (X-Ray)
 *   and stage `variables` are set on the RestApi's `deployOptions`
 *   (CDK L2 `apigateway.StageOptions`). They ride on the Stage's own
 *   CreateStage / UpdateStage API call (NOT a separate control-plane call),
 *   and verify.sh asserts both reached AWS via `aws apigateway get-stage`.
 *
 * covers: AWS::ApiGateway::Method
 * covers: AWS::ApiGateway::Resource
 * covers: AWS::ApiGateway::Stage
 * covers: AWS::ApiGateway::Deployment
 */
export class ApiGatewayStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create Lambda function with inline code
    const handler = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_20_X,
      code: lambda.Code.fromInline(`
exports.handler = async (event) => {
  return {
    statusCode: 200,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      message: "Hello from cdkd!",
      timestamp: new Date().toISOString(),
    }),
  };
};
      `.trim()),
      handler: 'index.handler',
      timeout: cdk.Duration.seconds(10),
    });

    // Create REST API Gateway. `defaultCorsPreflightOptions` auto-generates
    // an OPTIONS method on every resource that has any non-OPTIONS method,
    // each one carrying both `Integration.IntegrationResponses` and
    // `MethodResponses`.
    //
    // `cloudWatchRole: false` skips CDK's auto-emitted `AWS::ApiGateway::Account`
    // + its IAM Role for stage access logging. Both are emitted with
    // `DeletionPolicy: Retain` (the Account resource is account-scoped
    // singleton; CDK retains the supporting role by inference). On every
    // re-run of this integ test, the previously-retained IAM Role
    // (`<StackName>-HelloApiCloudWatchRole...`) blocks the next deploy with
    // `Role with name ... already exists`. The CloudWatch logging path is
    // not exercised by this smoke test, so disabling it altogether is the
    // cleanest way to keep the fixture self-contained across runs.
    const api = new apigateway.RestApi(this, 'HelloApi', {
      restApiName: 'cdkd-hello-api',
      description: 'A simple API Gateway + Lambda example for cdkd testing',
      cloudWatchRole: false,
      // Stage config props backfilled for issue #609. `deployOptions` is the
      // CDK L2 surface for the auto-created `prod` Stage; `tracingEnabled` +
      // `variables` synthesize as `TracingEnabled` / `Variables` on the
      // AWS::ApiGateway::Stage resource and ride on CreateStage / UpdateStage.
      deployOptions: {
        tracingEnabled: true,
        variables: {
          appVersion: '1.0.0',
          featureFlag: 'enabled',
        },
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
      },
    });

    // Add GET /hello endpoint with Lambda integration
    const helloResource = api.root.addResource('hello');
    helloResource.addMethod('GET', new apigateway.LambdaIntegration(handler));

    // Outputs
    new cdk.CfnOutput(this, 'ApiUrl', {
      value: api.url,
      description: 'REST API URL',
    });

    new cdk.CfnOutput(this, 'ApiId', {
      value: api.restApiId,
      description: 'REST API ID',
    });

    new cdk.CfnOutput(this, 'FunctionName', {
      value: handler.functionName,
      description: 'Lambda function name',
    });

    new cdk.CfnOutput(this, 'FunctionArn', {
      value: handler.functionArn,
      description: 'Lambda function ARN',
    });
  }
}
