import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as apigateway from 'aws-cdk-lib/aws-apigateway';

/**
 * API Gateway + Lambda example stack
 *
 * Demonstrates:
 * - REST API Gateway creation via Cloud Control API
 * - Lambda function with inline code (no asset publishing needed)
 * - Lambda integration with API Gateway
 * - Multiple resource types in one stack (API Gateway, Lambda, IAM)
 * - CfnOutput resolution with Fn::Join for API URL
 * - CORS preflight OPTIONS auto-generated by `defaultCorsPreflightOptions`,
 *   which emits AWS::ApiGateway::Method resources carrying both
 *   `Integration.IntegrationResponses` and `MethodResponses`. The
 *   `MethodResponse` for each statusCode MUST be created before the
 *   matching `IntegrationResponse`, otherwise AWS rejects with
 *   "Invalid mapping expression specified: ... [No method response
 *    exists for method.]" (pre-PR bug; regression-covered here).
 *
 * - Stage config props backfilled for issue #609: `tracingEnabled` (X-Ray)
 *   and stage `variables` are set on the RestApi's `deployOptions`
 *   (CDK L2 `apigateway.StageOptions`). They ride on the Stage's own
 *   CreateStage / UpdateStage API call (NOT a separate control-plane call),
 *   and verify.sh asserts both reached AWS via `aws apigateway get-stage`.
 *
 * - Greedy `{proxy+}` resource with an ANY method (the LambdaRestApi proxy
 *   pattern). This is the most common API Gateway shape in real CDK apps, and
 *   it exercises a path the explicit `GET /hello` method does not: a greedy
 *   proxy Resource + an ANY Method + the implicit
 *   Deployment-depends-on-the-proxy-Method DAG edge (getting that order wrong
 *   makes the Deployment snapshot miss the new method). verify.sh curls an
 *   arbitrary sub-path and asserts it reaches the Lambda.
 *
 * - Request validation: a Model (JSON schema) + RequestValidator + a POST
 *   method referencing both. Regression-covers the `Ref` resolution fix for
 *   AWS::ApiGateway::Model (Ref -> model name) and ::RequestValidator (Ref ->
 *   validator id) — both Cloud-Control-provisioned, so their physical id is the
 *   compound `<restApiId>|<ref>` while CFn's Ref returns only `<ref>`. Passing
 *   the compound id made API Gateway reject the method with "Invalid model
 *   identifier specified" / "Invalid Request Validator identifier specified".
 *   verify.sh curls a valid + invalid body and asserts 200 / 400.
 *
 * covers: AWS::ApiGateway::Method
 * covers: AWS::ApiGateway::Resource
 * covers: AWS::ApiGateway::Stage
 * covers: AWS::ApiGateway::Deployment
 * covers: AWS::ApiGateway::Model
 * covers: AWS::ApiGateway::RequestValidator
 */
export class ApiGatewayStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create Lambda function with inline code
    const handler = new lambda.Function(this, 'HelloHandler', {
      runtime: lambda.Runtime.NODEJS_20_X,
      code: lambda.Code.fromInline(`
exports.handler = async (event) => {
  return {
    statusCode: 200,
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      message: "Hello from cdkd!",
      timestamp: new Date().toISOString(),
    }),
  };
};
      `.trim()),
      handler: 'index.handler',
      timeout: cdk.Duration.seconds(10),
    });

    // Create REST API Gateway. `defaultCorsPreflightOptions` auto-generates
    // an OPTIONS method on every resource that has any non-OPTIONS method,
    // each one carrying both `Integration.IntegrationResponses` and
    // `MethodResponses`.
    //
    // `cloudWatchRole: false` skips CDK's auto-emitted `AWS::ApiGateway::Account`
    // + its IAM Role for stage access logging. Both are emitted with
    // `DeletionPolicy: Retain` (the Account resource is account-scoped
    // singleton; CDK retains the supporting role by inference). On every
    // re-run of this integ test, the previously-retained IAM Role
    // (`<StackName>-HelloApiCloudWatchRole...`) blocks the next deploy with
    // `Role with name ... already exists`. The CloudWatch logging path is
    // not exercised by this smoke test, so disabling it altogether is the
    // cleanest way to keep the fixture self-contained across runs.
    const api = new apigateway.RestApi(this, 'HelloApi', {
      restApiName: 'cdkd-hello-api',
      description: 'A simple API Gateway + Lambda example for cdkd testing',
      cloudWatchRole: false,
      // Stage config props backfilled for issue #609. `deployOptions` is the
      // CDK L2 surface for the auto-created `prod` Stage; `tracingEnabled` +
      // `variables` synthesize as `TracingEnabled` / `Variables` on the
      // AWS::ApiGateway::Stage resource and ride on CreateStage / UpdateStage.
      // `throttlingRateLimit` / `throttlingBurstLimit` synthesize as the
      // Stage's `MethodSettings` wildcard entry (issue #966): the SDK
      // provider applies them via a post-create UpdateStage patch, so the
      // Stage stays on the SDK fast path instead of CC-routing (#963's
      // trigger). verify.sh asserts the throttling reached AWS AND that the
      // Stage was NOT CC-routed.
      deployOptions: {
        tracingEnabled: true,
        throttlingRateLimit: 100,
        throttlingBurstLimit: 50,
        variables: {
          appVersion: '1.0.0',
          featureFlag: 'enabled',
        },
      },
      defaultCorsPreflightOptions: {
        allowOrigins: apigateway.Cors.ALL_ORIGINS,
        allowMethods: apigateway.Cors.ALL_METHODS,
      },
    });

    // Add GET /hello endpoint with Lambda integration
    const helloResource = api.root.addResource('hello');
    helloResource.addMethod('GET', new apigateway.LambdaIntegration(handler));

    // Greedy {proxy+} resource with an ANY method — the LambdaRestApi proxy
    // pattern. Exercises the greedy proxy Resource + ANY Method + the implicit
    // Deployment-depends-on-the-proxy-Method DAG edge. verify.sh curls an
    // arbitrary sub-path to prove the proxy route reaches the Lambda.
    api.root.addProxy({
      defaultIntegration: new apigateway.LambdaIntegration(handler),
      anyMethod: true,
    });

    // Standalone REQUEST authorizer (not attached to any method - no IAM
    // role / lambda permission needed since it is never invoked). It exists
    // solely to exercise the #609 Authorizer `authType` backfill — a
    // customer-defined free-form label used by OpenAPI import/export
    // tooling with no functional impact on the deployed authorizer. The
    // verify.sh asserts `aws apigateway get-authorizer --query 'authType'`
    // returns 'custom' post-deploy.
    new apigateway.CfnAuthorizer(this, 'RequestAuthorizer', {
      restApiId: api.restApiId,
      type: 'REQUEST',
      name: 'cdkd-request-authorizer',
      authType: 'custom',
      authorizerUri: `arn:aws:apigateway:${this.region}:lambda:path/2015-03-31/functions/${handler.functionArn}/invocations`,
      identitySource: 'method.request.header.Authorization',
    });

    // Request validation: a Model (JSON schema) + a RequestValidator + a POST
    // method that references BOTH. Regression-covers the `Ref` resolution fix
    // for the two API Gateway child types that are Cloud-Control-provisioned
    // (no SDK provider), so cdkd's physical id is the compound
    // `<restApiId>|<ref>` while CFn's `Ref` returns only the `<ref>` segment:
    //   - AWS::ApiGateway::Model — `RequestModels` value `{ Ref: <Model> }`
    //     must resolve to the model NAME, not `<restApiId>|<name>`, else AWS
    //     rejects the method with "Invalid model identifier specified".
    //   - AWS::ApiGateway::RequestValidator — `RequestValidatorId` value
    //     `{ Ref: <Validator> }` must resolve to the validator id, not
    //     `<restApiId>|<id>`, else AWS rejects with "Invalid Request Validator
    //     identifier specified".
    // verify.sh curls a valid + an invalid body and asserts 200 / 400.
    const petModel = api.addModel('PetModel', {
      contentType: 'application/json',
      modelName: 'Pet',
      schema: {
        schema: apigateway.JsonSchemaVersion.DRAFT4,
        title: 'Pet',
        type: apigateway.JsonSchemaType.OBJECT,
        required: ['name'],
        properties: {
          name: { type: apigateway.JsonSchemaType.STRING },
          age: { type: apigateway.JsonSchemaType.INTEGER },
        },
      },
    });
    const bodyValidator = api.addRequestValidator('BodyValidator', {
      validateRequestBody: true,
      validateRequestParameters: false,
    });
    const pets = api.root.addResource('pets');
    pets.addMethod('POST', new apigateway.LambdaIntegration(handler), {
      requestValidator: bodyValidator,
      requestModels: { 'application/json': petModel },
    });

    // Outputs
    new cdk.CfnOutput(this, 'ApiUrl', {
      value: api.url,
      description: 'REST API URL',
    });

    new cdk.CfnOutput(this, 'ApiId', {
      value: api.restApiId,
      description: 'REST API ID',
    });

    new cdk.CfnOutput(this, 'FunctionName', {
      value: handler.functionName,
      description: 'Lambda function name',
    });

    new cdk.CfnOutput(this, 'FunctionArn', {
      value: handler.functionArn,
      description: 'Lambda function ARN',
    });
  }
}
