import * as cdk from 'aws-cdk-lib';
import type { Construct } from 'constructs';

/**
 * A resource whose `Type` changes on an EXISTING logical id (issues
 * [#2668](https://github.com/go-to-k/cdkd/issues/2668) and
 * [#3036](https://github.com/go-to-k/cdkd/issues/3036)).
 *
 * Three rows keep their logical id while `TYPE_VARIANT` moves their type:
 *
 * | logical id  | `v1` (default)                | `v2`                          |
 * | ----------- | ----------------------------- | ----------------------------- |
 * | `Subject`   | `AWS::SSM::Parameter` (named) | `AWS::SNS::Topic` (named)     |
 * | `Overlap`   | `AWS::SSM::Parameter` (named) | `AWS::Logs::LogGroup`, SAME name |
 * | `EqualBags` | `AWS::SNS::Topic`, `Tags` only | `AWS::Logs::LogGroup`, SAME `Tags` |
 *
 * - `Subject` leaves a STATEFUL type for a non-stateful one. The stateful guard
 *   has to evaluate the type being DESTROYED; keyed on the template's type it
 *   never fired for this row.
 * - `Overlap` is the overlapping-namespace case: an SSM parameter and a log
 *   group are both addressed by a bare name, so the two physical ids are EQUAL.
 *   A delete dispatched at the new type's provider deletes the log group the
 *   deploy just created; an "equal id means the same resource" shortcut strands
 *   one of the two.
 * - `EqualBags` declares the SAME property bag under both types — the #3036
 *   shape, which the UPDATE arm's properties-only no-op skip used to swallow
 *   under a green deploy. Both names are generated by cdkd, deterministically.
 *
 * The rows are chained (`Overlap` after `Subject`, `EqualBags` after `Overlap`)
 * so a deploy that refuses `Subject` reaches neither of the others, which keeps
 * the refusal arm deterministic.
 *
 * `INJECT_FAIL=true` adds a queue AWS rejects at create time, downstream of all
 * three rows, so the deploy fails AFTER the replacements completed — the state
 * a rollback has to reverse.
 *
 * L1 constructs throughout: the logical id is pinned with `overrideLogicalId`,
 * and nothing here takes an L2's default `Retain`.
 *
 * covers: AWS::SSM::Parameter
 * covers: AWS::SNS::Topic
 * covers: AWS::Logs::LogGroup
 */
export class TypeChangeReplacementStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const variant = process.env.TYPE_VARIANT ?? 'v1';
    if (variant !== 'v1' && variant !== 'v2') {
      throw new Error(`TYPE_VARIANT must be v1 or v2 (got ${variant})`);
    }
    const typeChanged = variant === 'v2';

    const subject: cdk.CfnResource = typeChanged
      ? new cdk.aws_sns.CfnTopic(this, 'SubjectTopic', {
          topicName: `${this.stackName}-subject`,
        })
      : new cdk.aws_ssm.CfnParameter(this, 'SubjectParameter', {
          name: `/cdkd-integ/${this.stackName}/subject`,
          type: 'String',
          value: 'type-change-subject',
        });
    subject.overrideLogicalId('Subject');

    // ONE name for both types: that is the row's whole point.
    const overlapName = `/cdkd-integ/${this.stackName}/overlap`;
    const overlap: cdk.CfnResource = typeChanged
      ? new cdk.aws_logs.CfnLogGroup(this, 'OverlapLogGroup', { logGroupName: overlapName })
      : new cdk.aws_ssm.CfnParameter(this, 'OverlapParameter', {
          name: overlapName,
          type: 'String',
          value: 'type-change-overlap',
        });
    overlap.overrideLogicalId('Overlap');
    overlap.addDependency(subject);

    // ONE bag for both types.
    const equalBagTags = [{ key: 'cdkd-integ-fixture', value: this.stackName }];
    const equalBags: cdk.CfnResource = typeChanged
      ? new cdk.aws_logs.CfnLogGroup(this, 'EqualBagsLogGroup', { tags: equalBagTags })
      : new cdk.aws_sns.CfnTopic(this, 'EqualBagsTopic', { tags: equalBagTags });
    equalBags.overrideLogicalId('EqualBags');
    equalBags.addDependency(overlap);

    if (process.env.INJECT_FAIL === 'true') {
      // Rejected by `CreateQueue` (the retention period is out of range), so
      // nothing is created and there is no name cooldown to wait out.
      const failing = new cdk.aws_sqs.CfnQueue(this, 'FailingQueue', {
        queueName: `${this.stackName}-failing-queue`,
        messageRetentionPeriod: 9999999,
      });
      failing.overrideLogicalId('FailingQueue');
      failing.addDependency(equalBags);
    }
  }
}
