import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as dynamodb from 'aws-cdk-lib/aws-dynamodb';
import * as lambda from 'aws-cdk-lib/aws-lambda';
import * as sns from 'aws-cdk-lib/aws-sns';
import * as sqs from 'aws-cdk-lib/aws-sqs';
import * as subscriptions from 'aws-cdk-lib/aws-sns-subscriptions';
import * as logs from 'aws-cdk-lib/aws-logs';
import * as cloudwatch from 'aws-cdk-lib/aws-cloudwatch';
import * as cloudwatch_actions from 'aws-cdk-lib/aws-cloudwatch-actions';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';

/**
 * Full Stack Demo - Serverless API Backend
 *
 * A realistic serverless application showcasing cdkd's ability to deploy
 * 15+ AWS resources with complex dependencies via Cloud Control API.
 *
 * Architecture:
 *   Client -> Lambda Function URL -> Lambda -> DynamoDB
 *                                          -> S3 (file storage)
 *                                          -> SNS -> SQS (async processing)
 *                                                 -> DLQ (failed messages)
 *   Secrets Manager (API key)
 *   CloudWatch Log Group + Alarm -> SNS (alerts)
 *
 * Resources created (15+):
 *   1. DynamoDB Table (with stream)
 *   2. Lambda Function (inline Python CRUD handler)
 *   3. Lambda Function URL (public access)
 *   4. SNS Topic (notifications)
 *   5. SQS Queue (async processing)
 *   6. SQS Dead Letter Queue
 *   7. S3 Bucket (file storage)
 *   8. Secrets Manager Secret (API key)
 *   9. CloudWatch Log Group (with retention)
 *  10. CloudWatch Alarm (Lambda errors)
 *  + IAM Roles, Policies, SQS Policy (auto-generated by CDK)
 *  + SNS Subscription, Lambda Permission
 */
export class FullStackDemoStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // ─── DynamoDB Table ───────────────────────────────────────────
    const table = new dynamodb.Table(this, 'ItemsTable', {
      partitionKey: {
        name: 'PK',
        type: dynamodb.AttributeType.STRING,
      },
      sortKey: {
        name: 'SK',
        type: dynamodb.AttributeType.STRING,
      },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      stream: dynamodb.StreamViewType.NEW_AND_OLD_IMAGES,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // ─── S3 Bucket (file storage) ────────────────────────────────
    const bucket = new s3.Bucket(this, 'FileStorage', {
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: false,
    });

    // ─── Secrets Manager (API key) ───────────────────────────────
    const apiKeySecret = new secretsmanager.Secret(this, 'ApiKeySecret', {
      description: 'API key for the full-stack demo application',
      generateSecretString: {
        excludePunctuation: true,
        passwordLength: 32,
      },
    });

    // ─── SNS Topic (notifications) ───────────────────────────────
    const notificationTopic = new sns.Topic(this, 'NotificationTopic', {
      displayName: 'Full Stack Demo Notifications',
    });

    // ─── SQS Dead Letter Queue ───────────────────────────────────
    const dlq = new sqs.Queue(this, 'DeadLetterQueue', {
      retentionPeriod: cdk.Duration.days(14),
    });

    // ─── SQS Queue (async processing) ────────────────────────────
    const processingQueue = new sqs.Queue(this, 'ProcessingQueue', {
      visibilityTimeout: cdk.Duration.seconds(60),
      deadLetterQueue: {
        queue: dlq,
        maxReceiveCount: 3,
      },
    });

    // Subscribe queue to SNS topic
    notificationTopic.addSubscription(
      new subscriptions.SqsSubscription(processingQueue)
    );

    // ─── CloudWatch Log Group ────────────────────────────────────
    const logGroup = new logs.LogGroup(this, 'ApiLogGroup', {
      logGroupName: `/cdkd/full-stack-demo/${this.stackName}`,
      retention: logs.RetentionDays.ONE_WEEK,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // ─── Lambda Function (inline Python CRUD handler) ────────────
    const handler = new lambda.Function(this, 'ApiHandler', {
      runtime: lambda.Runtime.PYTHON_3_12,
      handler: 'index.handler',
      code: lambda.Code.fromInline(`
import json
import os
import boto3
import logging
from datetime import datetime

logger = logging.getLogger()
logger.setLevel(logging.INFO)

dynamodb = boto3.resource('dynamodb')
table = dynamodb.Table(os.environ['TABLE_NAME'])
s3 = boto3.client('s3')
sns = boto3.client('sns')

def handler(event, context):
    logger.info(f"Received event: {json.dumps(event)}")
    method = event.get('requestContext', {}).get('http', {}).get('method', 'GET')
    path = event.get('rawPath', '/')

    try:
        if method == 'GET' and path == '/':
            return respond(200, {'message': 'Hello from cdkd!', 'service': 'full-stack-demo'})

        if method == 'GET' and path == '/items':
            result = table.scan(Limit=50)
            return respond(200, {'items': result.get('Items', [])})

        if method == 'POST' and path == '/items':
            body = json.loads(event.get('body', '{}'))
            item = {
                'PK': body.get('id', context.aws_request_id),
                'SK': datetime.utcnow().isoformat(),
                'data': body.get('data', ''),
                'createdAt': datetime.utcnow().isoformat(),
            }
            table.put_item(Item=item)
            # Publish notification
            sns.publish(
                TopicArn=os.environ['TOPIC_ARN'],
                Subject='New item created',
                Message=json.dumps({'itemId': item['PK'], 'action': 'created'}),
            )
            return respond(201, {'item': item})

        if method == 'DELETE' and path.startswith('/items/'):
            item_id = path.split('/')[-1]
            table.delete_item(Key={'PK': item_id, 'SK': item_id})
            return respond(200, {'deleted': item_id})

        return respond(404, {'error': 'Not found'})
    except Exception as e:
        logger.error(f"Error: {str(e)}")
        return respond(500, {'error': str(e)})

def respond(status_code, body):
    return {
        'statusCode': status_code,
        'headers': {'Content-Type': 'application/json'},
        'body': json.dumps(body, default=str),
    }
`),
      environment: {
        TABLE_NAME: table.tableName,
        BUCKET_NAME: bucket.bucketName,
        TOPIC_ARN: notificationTopic.topicArn,
        SECRET_ARN: apiKeySecret.secretArn,
      },
      timeout: cdk.Duration.seconds(30),
      memorySize: 256,
      logGroup: logGroup,
    });

    // ─── Lambda Function URL (public access) ─────────────────────
    const functionUrl = handler.addFunctionUrl({
      authType: lambda.FunctionUrlAuthType.NONE,
    });

    // ─── Permissions ─────────────────────────────────────────────
    table.grantReadWriteData(handler);
    bucket.grantReadWrite(handler);
    notificationTopic.grantPublish(handler);
    apiKeySecret.grantRead(handler);

    // ─── CloudWatch Alarm (Lambda errors) ────────────────────────
    const errorAlarm = new cloudwatch.Alarm(this, 'ApiErrorAlarm', {
      alarmDescription: 'Alarm when API handler has errors',
      metric: handler.metricErrors({
        period: cdk.Duration.minutes(5),
        statistic: 'Sum',
      }),
      threshold: 1,
      comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_OR_EQUAL_TO_THRESHOLD,
      evaluationPeriods: 1,
      treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
    });

    errorAlarm.addAlarmAction(new cloudwatch_actions.SnsAction(notificationTopic));

    // ─── Outputs ─────────────────────────────────────────────────
    new cdk.CfnOutput(this, 'FunctionUrl', {
      value: functionUrl.url,
      description: 'Lambda Function URL (public endpoint)',
    });

    new cdk.CfnOutput(this, 'TableName', {
      value: table.tableName,
      description: 'DynamoDB table name',
    });

    new cdk.CfnOutput(this, 'QueueUrl', {
      value: processingQueue.queueUrl,
      description: 'SQS processing queue URL',
    });

    new cdk.CfnOutput(this, 'TopicArn', {
      value: notificationTopic.topicArn,
      description: 'SNS notification topic ARN',
    });

    new cdk.CfnOutput(this, 'BucketName', {
      value: bucket.bucketName,
      description: 'S3 file storage bucket name',
    });

    new cdk.CfnOutput(this, 'SecretArn', {
      value: apiKeySecret.secretArn,
      description: 'Secrets Manager API key ARN',
    });

    new cdk.CfnOutput(this, 'AlarmArn', {
      value: errorAlarm.alarmArn,
      description: 'CloudWatch error alarm ARN',
    });
  }
}
