import { describe, it, expect, beforeEach, afterEach } from 'vite-plus/test';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import {
  parseRegisteredTypes,
  parseAllowNoIntegRationalesContent,
  parseImportAliases,
  scanL1Types,
  scanL2Types,
  scanLiteralTypes,
  listFixtures,
} from '../../../scripts/build-integ-coverage-matrix.js';

describe('parseRegisteredTypes', () => {
  it('extracts every registry.register("AWS::Service::Type", ...) call', () => {
    const src = `
      registry.register('AWS::IAM::Role', new IAMRoleProvider());
      registry.register("AWS::S3::Bucket", new S3BucketProvider());
      registry.register('AWS::Lambda::Function', new LambdaFunctionProvider());
    `;
    expect(parseRegisteredTypes(src)).toEqual([
      'AWS::IAM::Role',
      'AWS::Lambda::Function',
      'AWS::S3::Bucket',
    ]);
  });

  it('returns a sorted, deduplicated list', () => {
    const src = `
      registry.register('AWS::IAM::Role', new IAMRoleProvider());
      registry.register('AWS::S3::Bucket', new S3BucketProvider());
      registry.register('AWS::IAM::Role', anotherInstance);
    `;
    expect(parseRegisteredTypes(src)).toEqual(['AWS::IAM::Role', 'AWS::S3::Bucket']);
  });

  it('returns empty array for source without any register calls', () => {
    expect(parseRegisteredTypes('export function noop() {}')).toEqual([]);
  });

  it('matches commented-out lines too (regex is content-blind, by design)', () => {
    // The parser matches any `registry.register('AWS::Foo::Bar', ...)`
    // text — including inside a `//` comment. This is acceptable because
    // register-providers.ts is generated by hand from a fixed template
    // and commented-out registrations are not a real pattern in cdkd.
    // The hook's diff-based extraction (`^\+ *registry\.register\(...`)
    // is stricter; this script's job is to enumerate REGISTERED types,
    // and a commented-out line is treated as documentation noise rather
    // than a hidden orphan-trigger.
    const src = `
      // registry.register('AWS::Should::Ignore', ...)
      registry.register('AWS::Real::Type', new Provider());
    `;
    const result = parseRegisteredTypes(src);
    expect(result).toContain('AWS::Real::Type');
    expect(result).toContain('AWS::Should::Ignore');
  });

  it('does NOT match bare AWS::*:: string references outside `registry.register(`', () => {
    const src = `
      const docstring = 'AWS::Foo::Bar';
      registry.register('AWS::Real::Type', new Provider());
    `;
    expect(parseRegisteredTypes(src)).toEqual(['AWS::Real::Type']);
  });
});

describe('parseAllowNoIntegRationalesContent', () => {
  it('returns a Map of type -> non-empty rationale', () => {
    const json = JSON.stringify({
      'AWS::Foo::Bar': 'because reasons',
      'AWS::Baz::Qux': 'another reason',
    });
    const result = parseAllowNoIntegRationalesContent(json);
    expect(result.get('AWS::Foo::Bar')).toBe('because reasons');
    expect(result.get('AWS::Baz::Qux')).toBe('another reason');
    expect(result.size).toBe(2);
  });

  it('skips `$`-prefixed documentation keys', () => {
    const json = JSON.stringify({
      $schema: 'docs',
      '$why-sidecar': 'more docs',
      'AWS::Foo::Bar': 'real rationale',
    });
    const result = parseAllowNoIntegRationalesContent(json);
    expect(result.has('$schema')).toBe(false);
    expect(result.has('$why-sidecar')).toBe(false);
    expect(result.get('AWS::Foo::Bar')).toBe('real rationale');
  });

  it('rejects whitespace-only rationales (matches hook + matches gate)', () => {
    const json = JSON.stringify({
      'AWS::Empty::Value': '',
      'AWS::Whitespace::Only': '   \t\n',
      'AWS::Valid::Entry': 'real',
    });
    const result = parseAllowNoIntegRationalesContent(json);
    expect(result.has('AWS::Empty::Value')).toBe(false);
    expect(result.has('AWS::Whitespace::Only')).toBe(false);
    expect(result.get('AWS::Valid::Entry')).toBe('real');
  });

  it('rejects non-string values', () => {
    const json = JSON.stringify({
      'AWS::Object::Value': { reason: 'wrapped' },
      'AWS::Array::Value': ['list'],
      'AWS::Null::Value': null,
      'AWS::Number::Value': 42,
      'AWS::Valid::Entry': 'ok',
    });
    const result = parseAllowNoIntegRationalesContent(json);
    expect(result.has('AWS::Object::Value')).toBe(false);
    expect(result.has('AWS::Array::Value')).toBe(false);
    expect(result.has('AWS::Null::Value')).toBe(false);
    expect(result.has('AWS::Number::Value')).toBe(false);
    expect(result.get('AWS::Valid::Entry')).toBe('ok');
  });

  it('returns an empty Map for malformed JSON', () => {
    expect(parseAllowNoIntegRationalesContent('not json').size).toBe(0);
    expect(parseAllowNoIntegRationalesContent('').size).toBe(0);
    expect(parseAllowNoIntegRationalesContent('{').size).toBe(0);
  });

  it('returns an empty Map for non-object JSON roots', () => {
    expect(parseAllowNoIntegRationalesContent('null').size).toBe(0);
    expect(parseAllowNoIntegRationalesContent('[]').size).toBe(0);
    expect(parseAllowNoIntegRationalesContent('"a string"').size).toBe(0);
    expect(parseAllowNoIntegRationalesContent('42').size).toBe(0);
  });

  it('trims surrounding whitespace from rationale values', () => {
    const json = JSON.stringify({ 'AWS::X::Y': '  padded text  ' });
    const result = parseAllowNoIntegRationalesContent(json);
    expect(result.get('AWS::X::Y')).toBe('padded text');
  });
});

describe('parseImportAliases', () => {
  it('parses `import * as <alias> from "aws-cdk-lib/aws-<service>"` lines', () => {
    const src = `
      import * as s3 from 'aws-cdk-lib/aws-s3';
      import * as lambda from 'aws-cdk-lib/aws-lambda';
      import * as ec2 from 'aws-cdk-lib/aws-ec2';
    `;
    expect(parseImportAliases(src)).toEqual([
      { alias: 's3', module: 's3' },
      { alias: 'lambda', module: 'lambda' },
      { alias: 'ec2', module: 'ec2' },
    ]);
  });

  it('parses `aws_<svc> as <alias>` named-import shape', () => {
    const src = `import { aws_s3 as s3, aws_lambda as lambda } from 'aws-cdk-lib';`;
    expect(parseImportAliases(src)).toEqual([
      { alias: 's3', module: 's3' },
      { alias: 'lambda', module: 'lambda' },
    ]);
  });

  it('handles double-quoted and underscore-containing module names', () => {
    const src = `
      import * as logs from "aws-cdk-lib/aws-logs";
      import * as sfn_tasks from 'aws-cdk-lib/aws-stepfunctions-tasks';
    `;
    const result = parseImportAliases(src);
    expect(result).toContainEqual({ alias: 'logs', module: 'logs' });
    expect(result).toContainEqual({ alias: 'sfn_tasks', module: 'stepfunctions_tasks' });
  });

  it('returns empty array when no aws-cdk-lib imports present', () => {
    expect(parseImportAliases(`import { Construct } from 'constructs';`)).toEqual([]);
  });
});

describe('scanL1Types', () => {
  it('detects `new <ns>.Cfn<X>(` calls and maps to AWS::Service::X', () => {
    const src = `
      import * as sqs from 'aws-cdk-lib/aws-sqs';
      new sqs.CfnQueue(this, 'Q', { queueName: 'foo' });
    `;
    const aliases = parseImportAliases(src);
    const result = scanL1Types(src, aliases);
    expect(result.get('AWS::SQS::Queue')).toBe('l1');
  });

  it('returns an empty Map when no Cfn constructors appear', () => {
    const src = `import * as s3 from 'aws-cdk-lib/aws-s3'; new s3.Bucket(this, 'B', {});`;
    const aliases = parseImportAliases(src);
    expect(scanL1Types(src, aliases).size).toBe(0);
  });

  it('respects the alias -> AWS-service mapping for non-trivial casings', () => {
    const src = `
      import * as elbv2 from 'aws-cdk-lib/aws-elasticloadbalancingv2';
      new elbv2.CfnLoadBalancer(this, 'X', {});
    `;
    const aliases = parseImportAliases(src);
    const result = scanL1Types(src, aliases);
    expect(result.get('AWS::ElasticLoadBalancingV2::LoadBalancer')).toBe('l1');
  });

  it('handles multiple Cfn constructors in one file', () => {
    const src = `
      import * as ssm from 'aws-cdk-lib/aws-ssm';
      new ssm.CfnDocument(this, 'D', {});
      new ssm.CfnParameter(this, 'P', {});
    `;
    const aliases = parseImportAliases(src);
    const result = scanL1Types(src, aliases);
    expect(result.get('AWS::SSM::Document')).toBe('l1');
    expect(result.get('AWS::SSM::Parameter')).toBe('l1');
  });
});

describe('scanL2Types', () => {
  it('detects `new <ns>.<Construct>(` for known L2 constructs', () => {
    const src = `
      import * as s3 from 'aws-cdk-lib/aws-s3';
      new s3.Bucket(this, 'B', { versioned: true });
    `;
    const aliases = parseImportAliases(src);
    const result = scanL2Types(src, aliases);
    expect(result.get('AWS::S3::Bucket')).toBe('l2');
  });

  it('expands ec2.Vpc to multiple CFn types (VPC + Subnet + IGW + RouteTable + Route + ...)', () => {
    const src = `
      import * as ec2 from 'aws-cdk-lib/aws-ec2';
      new ec2.Vpc(this, 'V', { maxAzs: 2 });
    `;
    const aliases = parseImportAliases(src);
    const result = scanL2Types(src, aliases);
    expect(result.get('AWS::EC2::VPC')).toBe('l2');
    expect(result.get('AWS::EC2::Subnet')).toBe('l2');
    expect(result.get('AWS::EC2::InternetGateway')).toBe('l2');
    expect(result.get('AWS::EC2::RouteTable')).toBe('l2');
    expect(result.get('AWS::EC2::Route')).toBe('l2');
    expect(result.get('AWS::EC2::SubnetRouteTableAssociation')).toBe('l2');
    expect(result.get('AWS::EC2::NatGateway')).toBe('l2');
    expect(result.get('AWS::EC2::VPCGatewayAttachment')).toBe('l2');
  });

  it('returns an empty Map for unknown L2 construct names', () => {
    const src = `
      import * as s3 from 'aws-cdk-lib/aws-s3';
      new s3.NotARealConstruct(this, 'X', {});
    `;
    const aliases = parseImportAliases(src);
    expect(scanL2Types(src, aliases).size).toBe(0);
  });

  it('only emits l2 signal (not l1 — that comes from a separate pass)', () => {
    const src = `
      import * as lambda from 'aws-cdk-lib/aws-lambda';
      new lambda.Function(this, 'F', {});
    `;
    const aliases = parseImportAliases(src);
    const result = scanL2Types(src, aliases);
    expect(Array.from(result.values())).toEqual(['l2']);
  });
});

describe('scanLiteralTypes', () => {
  it('detects quoted `AWS::Service::Type` strings (CfnResource style)', () => {
    const src = `
      new cdk.CfnResource(this, 'R', {
        type: 'AWS::SSM::Document',
        properties: {},
      });
    `;
    expect(scanLiteralTypes(src).get('AWS::SSM::Document')).toBe('literal');
  });

  it('detects bare `AWS::Service::Type` references in comments', () => {
    // The contract: `// covers: AWS::Foo::Bar` documentation comments
    // count as a contributor-asserted coverage claim. The matrix does
    // not verify the claim — that is documentation lie territory, not
    // a hidden orphan.
    const src = `
      // covers: AWS::Lambda::Function
      // and also AWS::DynamoDB::Table
      export class FooStack {}
    `;
    const result = scanLiteralTypes(src);
    expect(result.get('AWS::Lambda::Function')).toBe('literal');
    expect(result.get('AWS::DynamoDB::Table')).toBe('literal');
  });

  it('returns empty for source without AWS::*:: tokens', () => {
    expect(scanLiteralTypes(`const x = 1;`).size).toBe(0);
  });

  it('deduplicates multiple mentions of the same type', () => {
    const src = `
      // AWS::S3::Bucket
      // AWS::S3::Bucket again
      'AWS::S3::Bucket'
    `;
    const result = scanLiteralTypes(src);
    expect(result.size).toBe(1);
    expect(result.get('AWS::S3::Bucket')).toBe('literal');
  });
});

describe('listFixtures', () => {
  let tmpRoot: string;
  beforeEach(() => {
    tmpRoot = mkdtempSync(join(tmpdir(), 'integ-cov-list-'));
  });
  afterEach(() => {
    rmSync(tmpRoot, { recursive: true, force: true });
  });

  it('returns an empty list when the directory does not exist', () => {
    expect(listFixtures(join(tmpRoot, 'nope'))).toEqual([]);
  });

  it('lists immediate-child directories only, sorted', () => {
    mkdirSync(join(tmpRoot, 'b-fixture'));
    mkdirSync(join(tmpRoot, 'a-fixture'));
    writeFileSync(join(tmpRoot, 'not-a-dir.txt'), '');
    expect(listFixtures(tmpRoot)).toEqual(['a-fixture', 'b-fixture']);
  });

  it('skips hidden directories (`.foo/`, `.scratch/`)', () => {
    mkdirSync(join(tmpRoot, 'a-fixture'));
    mkdirSync(join(tmpRoot, '.hidden'));
    mkdirSync(join(tmpRoot, '.scratch'));
    expect(listFixtures(tmpRoot)).toEqual(['a-fixture']);
  });
});
