/**
 * Helpers for cdkd's deploy-time property-coverage pre-flight check.
 *
 * The data ({@link PROPERTY_COVERAGE_BY_TYPE}) is generated by
 * `scripts/gen-property-coverage.ts` (run via `vp run gen:property-coverage`)
 * from the CFn schema fixtures (`tests/fixtures/cfn-schemas/*.json`) and
 * each SDK provider's `handledProperties` / `unhandledByDesign` declarations.
 * This module adds the runtime predicates + the actionable issue link used
 * by the pre-flight check (see {@link ./provider-registry.ProviderRegistry.validateResourceProperties}).
 *
 * The pre-flight rejects deploys whose templates use top-level CFn properties
 * for which cdkd's SDK provider does not write to AWS (= silent drop). The
 * user can opt in to the silent drop on a per-property basis via
 * `--allow-unsupported-properties <Type:Prop>,...`. v0 stance: silent drop
 * is a bug; explicit opt-in is required to proceed.
 */
import { type PropertyCoverage, PROPERTY_COVERAGE_BY_TYPE } from './property-coverage.generated.js';

export { PROPERTY_COVERAGE_BY_TYPE };
export type { PropertyCoverage };

/**
 * Look up a Tier 1 type's property-coverage record. Returns `undefined` for
 * Tier 2 (CC API) types (deliberately not in the map — CC forwards the full
 * property map to AWS, so there is no write-side silent drop at cdkd) and
 * for unknown / Custom types.
 */
export function getPropertyCoverage(resourceType: string): PropertyCoverage | undefined {
  return PROPERTY_COVERAGE_BY_TYPE.get(resourceType);
}

/**
 * Identify top-level template properties cdkd would silently drop on write
 * for a single resource. Returns an array of `{ property, rationale }` for
 * each unhandled top-level key in `templateProperties`, sorted alphabetically.
 *
 * Properties NOT in the CFn schema (likely a user typo or
 * `addPropertyOverride` escape hatch) are silently allowed: matching CFn's
 * own tolerance, and we cannot judge intent.
 */
export function findSilentDropProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined
): Array<{ property: string; rationale: string }> {
  if (!templateProperties) return [];
  const coverage = getPropertyCoverage(resourceType);
  if (!coverage) return []; // Tier 2 / Custom / unknown — pass through.
  const drops: Array<{ property: string; rationale: string }> = [];
  for (const prop of Object.keys(templateProperties)) {
    if (coverage.handled.has(prop)) continue;
    const rationale = coverage.silentDrop.get(prop);
    if (rationale === undefined) continue; // Not in schema (escape hatch / typo) — silently allow.
    drops.push({ property: prop, rationale });
  }
  return drops.sort((a, b) => a.property.localeCompare(b.property));
}

/**
 * A 1-click pre-filled GitHub issue link requesting cdkd support for a
 * specific top-level property on a resource type. Surfaced in the pre-flight
 * error so a user hitting a silent drop lands directly in the "request
 * support" flow.
 */
export function unsupportedPropertyIssueUrl(resourceType: string, property: string): string {
  const title = encodeURIComponent(`Support property ${resourceType}.${property}`);
  return `https://github.com/go-to-k/cdkd/issues/new?title=${title}&labels=resource-support`;
}
