/**
 * Helpers for cdkd's deploy-time property-coverage check.
 *
 * The data ({@link PROPERTY_COVERAGE_BY_TYPE}) is generated by
 * `scripts/gen-property-coverage.ts` (run via `vp run gen:property-coverage`)
 * from the CFn schema fixtures (`tests/fixtures/cfn-schemas/*.json`) and
 * each SDK provider's `handledProperties` / `unhandledByDesign` declarations.
 * This module adds the runtime predicates + the actionable issue link used
 * by the routing decision (see
 * {@link ./provider-registry.ProviderRegistry.getProviderFor} and
 * {@link ./provider-registry.ProviderRegistry.reportSilentDropDecisions}).
 *
 * Behavior: when a template uses a top-level CFn property cdkd's SDK
 * Provider does not write to AWS (= silent drop), the resource is
 * **auto-routed via Cloud Control API** by default — CC forwards the
 * full property map verbatim, closing the silent-drop bug (#614). The
 * user can opt out per-property via
 * `--allow-unsupported-properties <Type:Prop>,...`, which keeps the
 * resource on the SDK Provider path and accepts the silent drop (a
 * warn line is logged for auditability).
 */
import { isDeepStrictEqual } from 'node:util';
import { type PropertyCoverage, PROPERTY_COVERAGE_BY_TYPE } from './property-coverage.generated.js';
import { isNonProvisionable } from './unsupported-types.js';

export { PROPERTY_COVERAGE_BY_TYPE };
export type { PropertyCoverage };

/**
 * Look up a Tier 1 type's property-coverage record. Returns `undefined` for
 * Tier 2 (CC API) types (deliberately not in the map — CC forwards the full
 * property map to AWS, so there is no write-side silent drop at cdkd) and
 * for unknown / Custom types.
 */
export function getPropertyCoverage(resourceType: string): PropertyCoverage | undefined {
  return PROPERTY_COVERAGE_BY_TYPE.get(resourceType);
}

/**
 * Identify top-level template properties cdkd would silently drop on write
 * for a single resource. Returns an array of `{ property, rationale }` for
 * each unhandled top-level key in `templateProperties`, sorted alphabetically.
 *
 * Only properties the committed CFn schema snapshot KNOWS. A key absent from
 * it is {@link findUnrecognizedProperties}' concern, and it drives routing
 * through {@link findRoutableUnrecognizedProperties} instead — kept apart
 * because the state and diff NARROWINGS below read this list and must stay
 * fixture-only (issue [#3713](https://github.com/go-to-k/cdkd/issues/3713)).
 */
export function findSilentDropProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined
): Array<{ property: string; rationale: string }> {
  if (!templateProperties) return [];
  const coverage = getPropertyCoverage(resourceType);
  if (!coverage) return []; // Tier 2 / Custom / unknown — pass through.
  const drops: Array<{ property: string; rationale: string }> = [];
  for (const prop of Object.keys(templateProperties)) {
    if (coverage.handled.has(prop)) continue;
    const rationale = coverage.silentDrop.get(prop);
    if (rationale === undefined) continue; // Not in schema (escape hatch / typo) — silently allow.
    drops.push({ property: prop, rationale });
  }
  return drops.sort((a, b) => a.property.localeCompare(b.property));
}

/** Rationale carried by a route-driving key absent from the schema snapshot. */
export const UNRECOGNIZED_PROPERTY_RATIONALE = "not in cdkd's CFn schema snapshot";

/**
 * The properties that drive the Cloud Control auto-route (issue
 * [#614](https://github.com/go-to-k/cdkd/issues/614)): every silent drop whose
 * `<Type>:<Prop>` key is NOT in the `--prefer-sdk-route` allow set, plus every
 * {@link findRoutableUnrecognizedProperties} key. THE routing predicate —
 * `getProviderFor`, the sticky-escape, the plan and diff annotations and the
 * recreate validators all read it, so none can disagree with the route.
 *
 * `recordedProperties` is the resource's existing state-record bag, and it
 * matters only for the unrecognized half; see
 * {@link findRoutableUnrecognizedProperties}. Omitting it is PRESENCE
 * semantics, correct for a new physical resource.
 *
 * Sorted by property; `[]` for Tier 2 / Custom / unknown types, an absent bag,
 * or a bag whose every drop is allowed.
 */
export function findActionableSilentDrops(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined,
  allowedKeys: ReadonlySet<string>,
  recordedProperties?: Record<string, unknown>
): Array<{ property: string; rationale: string }> {
  const drops = findSilentDropProperties(resourceType, templateProperties).filter(
    ({ property }) => !allowedKeys.has(`${resourceType}:${property}`)
  );
  const unrecognized = findRoutableUnrecognizedProperties(
    resourceType,
    templateProperties,
    allowedKeys,
    recordedProperties
  );
  if (unrecognized.length === 0) return drops;
  return [
    ...drops,
    ...unrecognized.map((property) => ({ property, rationale: UNRECOGNIZED_PROPERTY_RATIONALE })),
  ].sort((a, b) => a.property.localeCompare(b.property));
}

/**
 * The {@link findUnrecognizedProperties} keys that route the resource through
 * Cloud Control (issue [#3713](https://github.com/go-to-k/cdkd/issues/3713)).
 *
 * A key the snapshot does not know is either a property AWS published after
 * it, a typo, or an `addPropertyOverride` escape hatch, and the SDK route
 * drops all three. Cloud Control applies the first and REJECTS the other two
 * with `Unsupported property`, which is what CloudFormation does too — so
 * routing is right for all three, and a rejected CREATE / UPDATE leaves the
 * state record (and its `provisionedBy`) untouched.
 *
 * Excluded, each derivable offline so the check stays a table lookup:
 *
 * - a READ-ONLY key — CloudFormation IGNORES one set in a template rather than
 *   rejecting it, so routing it would turn a working deploy into a failing one;
 * - a key in the `--prefer-sdk-route` allow set;
 * - every key on a type Cloud Control cannot take over (`ccRouteUnavailable`,
 *   or `NON_PROVISIONABLE`) — `getProviderFor` would otherwise REFUSE a
 *   template it deploys today;
 * - with `recordedProperties`, a key the record already holds with a
 *   deep-equal value. That is what keeps an EXISTING deployment where it is: a
 *   resource that deployed on the SDK route with such a key keeps deploying
 *   there, and only adding or changing the key moves it. Without it, an
 *   unrelated update would flip that resource to Cloud Control, which fails on
 *   a typo and on a type whose SDK physical id is not Cloud Control's
 *   identifier. Deliberately not applied by the sticky-escape
 *   (`wouldReturnToSdkProvider`), which must stay conservative.
 */
export function findRoutableUnrecognizedProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined,
  allowedKeys: ReadonlySet<string>,
  recordedProperties?: Record<string, unknown>
): string[] {
  const coverage = getPropertyCoverage(resourceType);
  if (!templateProperties || !coverage) return [];
  if (coverage.ccRouteUnavailable || isNonProvisionable(resourceType)) return [];
  return findUnrecognizedProperties(resourceType, templateProperties).filter(
    (property) =>
      !coverage.readOnly.has(property) &&
      !allowedKeys.has(`${resourceType}:${property}`) &&
      !(
        recordedProperties != null &&
        typeof recordedProperties === 'object' &&
        Object.hasOwn(recordedProperties, property) &&
        sameJsonValue(recordedProperties[property], templateProperties[property])
      )
  );
}

/**
 * Structural equality over the JSON form, for the baseline arm of
 * {@link findRoutableUnrecognizedProperties}. Not `isDeepStrictEqual` on the raw
 * values: the two bags are built by different code (the state record is parsed
 * JSON, the desired bag can be rebuilt with a null prototype by the secret
 * redaction), and a prototype difference must not read as a changed value —
 * that would route an unchanged key. Key order does not matter here either.
 */
function sameJsonValue(recorded: unknown, desired: unknown): boolean {
  const recordedJson = toJsonValue(recorded);
  // The record persists a dynamic-reference secret as its unresolved
  // `{{resolve:...}}` expression while the routing bag holds the resolved
  // value, so the two never compare equal. Such a key cannot be compared at
  // all; treating it as unchanged keeps the resource on the route it already
  // has, which is the safe direction for an existing deployment.
  if (JSON.stringify(recordedJson)?.includes('{{resolve:') === true) return true;
  const desiredJson = toJsonValue(desired);
  // The pre-flight report and `cdkd diff` read the template's RAW bag, where a
  // value can still be an intrinsic; the record holds its resolved form. Such
  // a value cannot be compared before resolution either, and treating it as
  // unchanged keeps those surfaces from announcing a Cloud Control route the
  // resolved routing decision does not take. The routing call sites pass
  // RESOLVED bags, so none of them reaches this arm.
  if (containsIntrinsic(desiredJson)) return true;
  return isDeepStrictEqual(recordedJson, desiredJson);
}

/** True when `value` holds a `Ref` / `Fn::*` object anywhere. */
function containsIntrinsic(value: unknown): boolean {
  if (Array.isArray(value)) return value.some(containsIntrinsic);
  if (value === null || typeof value !== 'object') return false;
  return Object.entries(value).some(
    ([key, child]) => key === 'Ref' || key.startsWith('Fn::') || containsIntrinsic(child)
  );
}

function toJsonValue(value: unknown): unknown {
  return value === undefined ? undefined : (JSON.parse(JSON.stringify(value)) as unknown);
}

/**
 * The silent-drop properties in `templateProperties` the user has opted back
 * INTO dropping via `--allow-unsupported-properties`, **and that this deploy
 * will therefore really fail to write** (issue
 * [#2750](https://github.com/go-to-k/cdkd/issues/2750)).
 *
 * Returns `[]` as soon as ONE drop is NOT in `allowedKeys`, which is the whole
 * point and not an optimization: that single un-allowed drop auto-routes the
 * **resource** through Cloud Control (issue
 * [#614](https://github.com/go-to-k/cdkd/issues/614)), and CC forwards the full
 * property map — so the allow-listed keys reach AWS too and nothing is dropped.
 * The allow set is per `<Type>:<Prop>` while the route is per RESOURCE, so a
 * per-property answer would be wrong for exactly the mixed bag.
 *
 * The complement of {@link findActionableSilentDrops}: one is empty whenever
 * the other is not, unless the bag has no drops at all (both empty). A
 * route-driving UNRECOGNIZED key empties this too, which is why it takes the
 * same `recordedProperties` — but the accepted list itself stays fixture-only,
 * since it feeds the narrowing.
 */
export function findAcceptedSilentDrops(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined,
  allowedKeys: ReadonlySet<string>,
  recordedProperties?: Record<string, unknown>
): string[] {
  if (
    findRoutableUnrecognizedProperties(
      resourceType,
      templateProperties,
      allowedKeys,
      recordedProperties
    ).length > 0
  ) {
    return [];
  }
  const drops = findSilentDropProperties(resourceType, templateProperties);
  const accepted: string[] = [];
  for (const { property } of drops) {
    if (!allowedKeys.has(`${resourceType}:${property}`)) return [];
    accepted.push(property);
  }
  return accepted;
}

/**
 * `properties` minus every top-level key this type's SDK Provider does not
 * write — i.e. what the SDK route ACTUALLY sends to AWS (issue
 * [#2750](https://github.com/go-to-k/cdkd/issues/2750)).
 *
 * Two callers, and both are about a bag that describes the SDK route:
 *
 * - the state record written after an SDK-routed create / update, so the record
 *   stops claiming a value AWS does not hold. Recording the template bag is
 *   what defeated the later Cloud Control re-route: `CloudControlProvider.update`
 *   builds its JSON Patch from the recorded bag, found the property identical on
 *   both sides, and omitted it;
 * - the CURRENT side of the diff for a resource recorded `provisionedBy: 'sdk'`.
 *   A silent-drop key in such a record is junk BY CONSTRUCTION (the SDK route
 *   cannot have written it), so removing it is what lets a pre-fix record heal:
 *   the key reads as an addition, the deploy auto-routes, and Cloud Control
 *   sends it.
 *
 * No allow set: on the SDK route every drop present is allow-listed already
 * (that is what kept the resource off the auto-route), and a record's own route
 * is read from `provisionedBy` rather than re-derived from flags a later deploy
 * may have changed. Returns the input UNCHANGED when nothing applies, so a
 * caller can compare by reference.
 */
export function withoutSilentDropProperties(
  resourceType: string,
  properties: Record<string, unknown>
): Record<string, unknown> {
  const removable = removableSilentDrops(resourceType, properties);
  if (removable.length === 0) return properties;
  const written = { ...properties };
  for (const property of removable) delete written[property];
  return written;
}

/**
 * `properties` minus the drops this deploy's flags have opted INTO
 * ({@link findAcceptedSilentDrops}) — the DESIRED side's twin of
 * {@link withoutSilentDropProperties} (issue
 * [#2750](https://github.com/go-to-k/cdkd/issues/2750)).
 *
 * Narrowing only the record and not the desired side is the failure mode the
 * `canonicalizeDesiredProperties` contract in `src/types/resource.ts` spells
 * out for issue [#1591](https://github.com/go-to-k/cdkd/issues/1591): the
 * template's key resurfaces as a change on EVERY later deploy, and for a
 * create-only property that change is a REPLACEMENT — a destroy-and-recreate
 * of a resource nobody touched. It takes the allow set (unlike the record-side
 * helper) because an un-allowed drop auto-routes to Cloud Control, which DOES
 * write the key, so narrowing it there would hide a real difference.
 *
 * It declines a CREATE-ONLY drop for the same reason its record-side twin does
 * — {@link removableSilentDrops} carries the rationale, and both go through
 * {@link excludeCreateOnly} so they cannot decline on different rules.
 *
 * `recordedProperties` is the resource's state-record bag — the one
 * `getProviderFor` receives as `previousProperties` — so this narrows on the
 * route the deploy actually takes (issue
 * [#3713](https://github.com/go-to-k/cdkd/issues/3713)). Omitting it for an
 * existing resource treats an unchanged unrecognized key as route-driving and
 * declines to narrow.
 *
 * Returns the input UNCHANGED when nothing applies.
 */
export function withoutAcceptedSilentDropProperties(
  resourceType: string,
  properties: Record<string, unknown>,
  allowedKeys: ReadonlySet<string>,
  recordedProperties?: Record<string, unknown>
): Record<string, unknown> {
  const removable = excludeCreateOnly(
    resourceType,
    findAcceptedSilentDrops(resourceType, properties, allowedKeys, recordedProperties)
  );
  if (removable.length === 0) return properties;
  const written = { ...properties };
  for (const property of removable) delete written[property];
  return written;
}

/**
 * The silent-drop properties in `properties` it is SAFE to remove from a bag
 * describing the SDK route — every drop except the ones this type's schema
 * marks CREATE-ONLY (issue
 * [#2750](https://github.com/go-to-k/cdkd/issues/2750)).
 *
 * A create-only drop is deliberately LEFT IN, and the exclusion is not a
 * refinement — it is what stops the narrowing being destructive. Removing such
 * a key makes it read as an ADDITION against the template on the next deploy,
 * and `createOnlyChangeRequiresReplacement` classifies an added create-only
 * path as a REPLACEMENT: a plain upgrade deploy over an unchanged template
 * would DELETE and re-CREATE the resource and cascade to its dependents, where
 * before the narrowing it did nothing at all. 24 types carry 80 such pairs in
 * the committed schema snapshot, `AWS::EC2::Subnet.AvailabilityZoneId` and
 * `AWS::RDS::DBCluster.SnapshotIdentifier` among them.
 *
 * The cost is stated rather than hidden: for those 80 pairs the record keeps
 * claiming a value AWS does not hold, so removing the flag does NOT deliver
 * the property — the go-to-k/cdkd#2750 behaviour survives there. Applying a
 * create-only property to a live resource REQUIRES a replacement, which cdkd
 * must not do as a side effect of a flag being dropped; issue
 * [#2790](https://github.com/go-to-k/cdkd/issues/2790) carries the residual.
 *
 * The snapshot is the authority here because the narrowing is SYNCHRONOUS,
 * while the diff's own classifier resolves `createOnlyProperties` from the
 * LIVE registry via `DescribeType`. A property create-only at runtime but not
 * in the snapshot is therefore still narrowed; the daily schema-refresh job is
 * what bounds that window.
 */
function removableSilentDrops(
  resourceType: string,
  properties: Record<string, unknown> | undefined
): string[] {
  return excludeCreateOnly(
    resourceType,
    findSilentDropProperties(resourceType, properties).map(({ property }) => property)
  );
}

/**
 * `names` minus this type's create-only drops — the ONE spelling of the
 * exclusion {@link removableSilentDrops} documents.
 *
 * Shared rather than repeated because the two narrowings it serves must decline
 * TOGETHER: narrowing one comparison side and not the other is the difference
 * the whole `canonicalizeDesiredProperties` contract exists to avoid, so a
 * second exclusion class added to one copy would reintroduce it silently.
 */
function excludeCreateOnly(resourceType: string, names: string[]): string[] {
  if (names.length === 0) return names;
  const createOnly = getPropertyCoverage(resourceType)?.createOnlyDrops;
  if (createOnly === undefined || createOnly.size === 0) return names;
  return names.filter((property) => !createOnly.has(property));
}

/**
 * A 1-click pre-filled GitHub issue link requesting cdkd support for a
 * specific top-level property on a resource type. Surfaced in the pre-flight
 * error so a user hitting a silent drop lands directly in the "request
 * support" flow.
 */
export function unsupportedPropertyIssueUrl(resourceType: string, property: string): string {
  const title = encodeURIComponent(`Support property ${resourceType}.${property}`);
  return `https://github.com/go-to-k/cdkd/issues/new?title=${title}&labels=resource-support`;
}

/**
 * Identify top-level template properties this type's committed CFn schema
 * snapshot does not know about at all — present in neither
 * `coverage.handled` nor `coverage.silentDrop` (issue
 * [#2718](https://github.com/go-to-k/cdkd/issues/2718)).
 *
 * The complement of {@link findSilentDropProperties}. The routing table is
 * built offline from `tests/fixtures/cfn-schemas/*.json`, so every property
 * AWS publishes AFTER that snapshot lands here — as does a typo or an
 * `addPropertyOverride` key. The route-driving subset is
 * {@link findRoutableUnrecognizedProperties} (issue
 * [#3713](https://github.com/go-to-k/cdkd/issues/3713)); what stays on the SDK
 * route (read-only keys, allow-listed or unchanged ones, types Cloud Control
 * cannot take) is what the caller's warn reports.
 *
 * **Why a warn built on this has no false-positive mode.** An SDK provider
 * writes only what it declares in `handledProperties`, so a top-level property
 * in neither set does not reach AWS under ANY of the three readings — a
 * post-snapshot AWS addition, a typo, or a deliberate `addPropertyOverride`.
 * "This value will not reach AWS" is true in all three, so the caller does not
 * have to guess intent, and at deploy time it could not: cdkd holds only the
 * template and the baked-in table. Firing on a typo is a feature rather than
 * noise — CloudFormation would have REJECTED that typo, so today's silence is
 * strictly the worst of the three behaviors.
 *
 * Deliberately NOT gated on the snapshot's age: the statement is true whatever
 * `generatedAt` says, and an age gate would trade the typo visibility away for
 * a wall-clock dependence.
 *
 * Returns `[]` for Tier 2 / Custom / unknown types (no coverage record — Cloud
 * Control forwards the full property map, so nothing is dropped) and sorts
 * alphabetically, mirroring {@link findSilentDropProperties}. The CALLER is
 * responsible for firing only when the resource actually resolves to the SDK
 * route; see `ProviderRegistry.reportSilentDropDecisions`.
 */
export function findUnrecognizedProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined
): string[] {
  if (!templateProperties) return [];
  const coverage = getPropertyCoverage(resourceType);
  if (!coverage) return [];
  const unrecognized: string[] = [];
  for (const prop of Object.keys(templateProperties)) {
    // An intrinsic KEY is not a property name, and reporting one would be the
    // only FALSE warn this predicate can emit. `Properties: { 'Fn::If': [...] }`
    // is legal CloudFormation (and what `CfnInclude` / a raw `addOverride`
    // produces), and `Ref` sits in the same position.
    //
    // Matched by PRESENCE, not as a sole key — that mirrors what the resolver
    // actually does. `IntrinsicFunctionResolver.resolveValue` dispatches on
    // `if ('Fn::If' in obj)` / `if ('Ref' in obj)`, so a MIXED bag is still
    // resolved as an intrinsic and its siblings are discarded. A sole-key rule
    // here (tried once, reverted) therefore re-introduced the false warn for
    // exactly the mixed shape: the resolver's own sole-key test lives only in
    // `detectUnknownIntrinsicKey`, which governs UNKNOWN keys, not this.
    if (prop === 'Ref' || prop.startsWith('Fn::')) continue;
    if (coverage.handled.has(prop)) continue;
    if (coverage.silentDrop.has(prop)) continue;
    unrecognized.push(prop);
  }
  return unrecognized.sort((a, b) => a.localeCompare(b));
}
