/**
 * Helpers for cdkd's deploy-time property-coverage check.
 *
 * The data ({@link PROPERTY_COVERAGE_BY_TYPE}) is generated by
 * `scripts/gen-property-coverage.ts` (run via `vp run gen:property-coverage`)
 * from the CFn schema fixtures (`tests/fixtures/cfn-schemas/*.json`) and
 * each SDK provider's `handledProperties` / `unhandledByDesign` declarations.
 * This module adds the runtime predicates + the actionable issue link used
 * by the routing decision (see
 * {@link ./provider-registry.ProviderRegistry.getProviderFor} and
 * {@link ./provider-registry.ProviderRegistry.reportSilentDropDecisions}).
 *
 * Behavior: when a template uses a top-level CFn property cdkd's SDK
 * Provider does not write to AWS (= silent drop), the resource is
 * **auto-routed via Cloud Control API** by default — CC forwards the
 * full property map verbatim, closing the silent-drop bug (#614). The
 * user can opt out per-property via
 * `--allow-unsupported-properties <Type:Prop>,...`, which keeps the
 * resource on the SDK Provider path and accepts the silent drop (a
 * warn line is logged for auditability).
 */
import { type PropertyCoverage, PROPERTY_COVERAGE_BY_TYPE } from './property-coverage.generated.js';

export { PROPERTY_COVERAGE_BY_TYPE };
export type { PropertyCoverage };

/**
 * Look up a Tier 1 type's property-coverage record. Returns `undefined` for
 * Tier 2 (CC API) types (deliberately not in the map — CC forwards the full
 * property map to AWS, so there is no write-side silent drop at cdkd) and
 * for unknown / Custom types.
 */
export function getPropertyCoverage(resourceType: string): PropertyCoverage | undefined {
  return PROPERTY_COVERAGE_BY_TYPE.get(resourceType);
}

/**
 * Identify top-level template properties cdkd would silently drop on write
 * for a single resource. Returns an array of `{ property, rationale }` for
 * each unhandled top-level key in `templateProperties`, sorted alphabetically.
 *
 * Properties NOT in the CFn schema (likely a user typo or
 * `addPropertyOverride` escape hatch) are silently allowed: matching CFn's
 * own tolerance, and we cannot judge intent.
 */
export function findSilentDropProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined
): Array<{ property: string; rationale: string }> {
  if (!templateProperties) return [];
  const coverage = getPropertyCoverage(resourceType);
  if (!coverage) return []; // Tier 2 / Custom / unknown — pass through.
  const drops: Array<{ property: string; rationale: string }> = [];
  for (const prop of Object.keys(templateProperties)) {
    if (coverage.handled.has(prop)) continue;
    const rationale = coverage.silentDrop.get(prop);
    if (rationale === undefined) continue; // Not in schema (escape hatch / typo) — silently allow.
    drops.push({ property: prop, rationale });
  }
  return drops.sort((a, b) => a.property.localeCompare(b.property));
}

/**
 * Same as {@link findSilentDropProperties} but filters out entries whose
 * `<Type>:<Prop>` key is in the supplied allow set (the
 * `--allow-unsupported-properties` user override). Returned drops are the
 * ones that should drive CC API auto-routing (issue
 * [#614](https://github.com/go-to-k/cdkd/issues/614)) — silent drops
 * the user has explicitly opted-into via the override are removed so the
 * resource stays on the SDK Provider path.
 *
 * Mirrors `findSilentDropProperties`'s sort + early-return behavior:
 * returns `[]` for Tier 2 / Custom / unknown types, undefined / empty
 * `templateProperties`, or when every drop is in `allowedKeys`.
 */
export function findActionableSilentDrops(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined,
  allowedKeys: ReadonlySet<string>
): Array<{ property: string; rationale: string }> {
  const drops = findSilentDropProperties(resourceType, templateProperties);
  if (drops.length === 0) return drops;
  return drops.filter(({ property }) => !allowedKeys.has(`${resourceType}:${property}`));
}

/**
 * A 1-click pre-filled GitHub issue link requesting cdkd support for a
 * specific top-level property on a resource type. Surfaced in the pre-flight
 * error so a user hitting a silent drop lands directly in the "request
 * support" flow.
 */
export function unsupportedPropertyIssueUrl(resourceType: string, property: string): string {
  const title = encodeURIComponent(`Support property ${resourceType}.${property}`);
  return `https://github.com/go-to-k/cdkd/issues/new?title=${title}&labels=resource-support`;
}

/**
 * Identify top-level template properties this type's committed CFn schema
 * snapshot does not know about at all — present in neither
 * `coverage.handled` nor `coverage.silentDrop` (issue
 * [#2718](https://github.com/go-to-k/cdkd/issues/2718)).
 *
 * The complement of {@link findSilentDropProperties}, which deliberately
 * PASSES these through: a property absent from the schema is indistinguishable
 * at deploy time from a user typo or an `addPropertyOverride` escape hatch, so
 * it cannot drive a routing decision. That tolerance is correct for routing
 * and wrong for silence — the routing table is built offline from
 * `tests/fixtures/cfn-schemas/*.json`, so every property AWS publishes AFTER
 * that snapshot lands here, and on the SDK route it reaches neither AWS nor an
 * error while the deploy reports success. That is the issue
 * [#614](https://github.com/go-to-k/cdkd/issues/614) failure class arriving
 * through the one input the #614 machinery cannot observe.
 *
 * **Why a warn built on this has no false-positive mode.** An SDK provider
 * writes only what it declares in `handledProperties`, so a top-level property
 * in neither set does not reach AWS under ANY of the three readings — a
 * post-snapshot AWS addition, a typo, or a deliberate `addPropertyOverride`.
 * "This value will not reach AWS" is true in all three, so the caller does not
 * have to guess intent, and at deploy time it could not: cdkd holds only the
 * template and the baked-in table. Firing on a typo is a feature rather than
 * noise — CloudFormation would have REJECTED that typo, so today's silence is
 * strictly the worst of the three behaviors.
 *
 * Deliberately NOT gated on the snapshot's age: the statement is true whatever
 * `generatedAt` says, and an age gate would trade the typo visibility away for
 * a wall-clock dependence.
 *
 * Returns `[]` for Tier 2 / Custom / unknown types (no coverage record — Cloud
 * Control forwards the full property map, so nothing is dropped) and sorts
 * alphabetically, mirroring {@link findSilentDropProperties}. The CALLER is
 * responsible for firing only when the resource actually resolves to the SDK
 * route; see `ProviderRegistry.reportSilentDropDecisions`.
 */
export function findUnrecognizedProperties(
  resourceType: string,
  templateProperties: Record<string, unknown> | undefined
): string[] {
  if (!templateProperties) return [];
  const coverage = getPropertyCoverage(resourceType);
  if (!coverage) return [];
  const unrecognized: string[] = [];
  for (const prop of Object.keys(templateProperties)) {
    if (coverage.handled.has(prop)) continue;
    if (coverage.silentDrop.has(prop)) continue;
    // A whole-bag intrinsic is not a property name. `Properties: { 'Fn::If':
    // [...] }` is legal CloudFormation (and what `CfnInclude` / a raw
    // `addOverride` can produce), and the resolver expands it into real
    // properties later — so reporting `Fn::If` as "not in the schema" would be
    // the one FALSE warn this predicate can emit. Skipped by prefix rather
    // than by an enumerated list: every intrinsic in this position is spelled
    // `Fn::*`, and a new one must not become a false warn the day AWS adds it.
    if (prop.startsWith('Fn::')) continue;
    unrecognized.push(prop);
  }
  return unrecognized.sort((a, b) => a.localeCompare(b));
}
