/**
 * go-to-k/cdkd#4655: whether the live resource under a journaled proven
 * orphan's physical id is still the one the failed CREATE made.
 *
 * A journaled orphan (`physicalIdRecoveredFromError`) is recorded by its
 * physical id. For a type whose physical id is a name the user chose, the
 * user can delete the orphan by hand and something cdkd does not track can
 * create another resource under the same name before the next successful
 * deploy settles the journal; deleting by that id would then delete the
 * unrelated resource. The write side journals the provider's
 * `resourceIdentity` token beside the id (`createdResourceIdentity`); the
 * success settle deletes such an orphan only when the live token still
 * matches.
 *
 * Leaf module: imports types and the sentinel only.
 */
import { RESOURCE_NOT_FOUND, type ResourceNotFound } from '../../types/resource.js';
import type { ProviderRegistry } from '../../provisioning/provider-registry.js';

/**
 * Types whose marked physical id is generated by AWS and never names a later
 * resource: a random id (`vpc-…`, `fs-…`, `j-…`, a KMS key UUID, an access
 * key id) or an ARN carrying a random or creation-time suffix (ELBv2, ACM,
 * a Kinesis stream consumer). A resource answering to that id IS the one the
 * failed CREATE made, so no identity is needed. Each entry was checked
 * against its provider's `markCreatedBeforeFailure` site; a type whose marked
 * id is a name, a name-built ARN or a composite of reusable keys (an API
 * Gateway stage name, a method's `restApiId|resourceId|httpMethod`) must
 * not be added.
 */
export const UNIQUE_PHYSICAL_ID_TYPES: ReadonlySet<string> = new Set([
  'AWS::EC2::VPC',
  'AWS::EC2::Subnet',
  // `publicIp|eipalloc-…`: the allocation id is never reused.
  'AWS::EC2::EIP',
  'AWS::EC2::NatGateway',
  'AWS::EC2::SecurityGroup',
  'AWS::EC2::Instance',
  'AWS::EFS::FileSystem',
  'AWS::EFS::MountTarget',
  'AWS::FSx::FileSystem',
  'AWS::KMS::Key',
  'AWS::CertificateManager::Certificate',
  'AWS::ElasticLoadBalancingV2::LoadBalancer',
  'AWS::ElasticLoadBalancingV2::TargetGroup',
  'AWS::ElasticLoadBalancingV2::Listener',
  'AWS::EMR::Cluster',
  'AWS::EMR::InstanceGroupConfig',
  'AWS::EMR::InstanceFleetConfig',
  'AWS::Cognito::UserPool',
  'AWS::Route53::HostedZone',
  'AWS::ServiceDiscovery::PrivateDnsNamespace',
  'AWS::ServiceDiscovery::PublicDnsNamespace',
  'AWS::ServiceDiscovery::HttpNamespace',
  'AWS::ServiceDiscovery::Service',
  // The marked id is the random `apiId`, not the ARN.
  'AWS::AppSync::GraphQLApi',
  'AWS::IAM::AccessKey',
  // `…/consumer/<name>:<creation epoch>`.
  'AWS::Kinesis::StreamConsumer',
]);

/**
 * Types whose orphan delete itself compares the live content with what the
 * failed CREATE wrote and clears only a match (go-to-k/cdkd#4612): the delete
 * is its own identity proof, so the settle needs no token for them.
 */
export const CONTENT_COMPARED_DELETE_TYPES: ReadonlySet<string> = new Set([
  'AWS::SQS::QueuePolicy',
  'AWS::SNS::TopicPolicy',
]);

/**
 * Types whose marked physical id lives in cdkd's own namespace, so nothing
 * outside cdkd can create a resource under it: a nested stack's
 * `arn:cdkd-local:…:nested-stack/<parent>/<logicalId>`, whose delete acts on
 * the child stack's own state record.
 */
export const CDKD_NAMESPACE_ID_TYPES: ReadonlySet<string> = new Set(['AWS::CloudFormation::Stack']);

/** Whether a proven orphan of `resourceType` needs a journaled identity before the settle deletes it. */
export function orphanDeleteNeedsIdentity(resourceType: string): boolean {
  return (
    !UNIQUE_PHYSICAL_ID_TYPES.has(resourceType) &&
    !CONTENT_COMPARED_DELETE_TYPES.has(resourceType) &&
    !CDKD_NAMESPACE_ID_TYPES.has(resourceType)
  );
}

/**
 * How long one identity read may take. No SDK client here sets a request
 * timeout, and the write side runs where a hung read would hold back the
 * journal write that is the orphan's only record.
 */
export const RESOURCE_IDENTITY_TIMEOUT_MS = 10_000;

/**
 * The provider's `resourceIdentity` for `physicalId`, asked through the
 * provider the orphan's delete would take. `RESOURCE_NOT_FOUND` when AWS
 * reports it gone; `undefined` for a provider without the method, any answer
 * that is not a non-empty string, any error (never thrown), and a read that
 * has not answered within `timeoutMs`.
 */
export async function readResourceIdentity(
  providerRegistry: Pick<ProviderRegistry, 'getProviderFor'>,
  target: {
    resourceType: string;
    physicalId: string;
    provisionedBy?: 'sdk' | 'cc-api' | undefined;
  },
  region: string,
  timeoutMs: number = RESOURCE_IDENTITY_TIMEOUT_MS
): Promise<string | ResourceNotFound | undefined> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timedOut = new Promise<undefined>((resolve) => {
    timer = setTimeout(() => resolve(undefined), timeoutMs);
  });
  try {
    return await Promise.race([askResourceIdentity(providerRegistry, target, region), timedOut]);
  } finally {
    clearTimeout(timer);
  }
}

async function askResourceIdentity(
  providerRegistry: Pick<ProviderRegistry, 'getProviderFor'>,
  target: {
    resourceType: string;
    physicalId: string;
    provisionedBy?: 'sdk' | 'cc-api' | undefined;
  },
  region: string
): Promise<string | ResourceNotFound | undefined> {
  try {
    const { provider } = providerRegistry.getProviderFor({
      resourceType: target.resourceType,
      provisionedBy: target.provisionedBy,
    });
    if (typeof provider.resourceIdentity !== 'function') return undefined;
    const identity = await provider.resourceIdentity(target.physicalId, target.resourceType, {
      expectedRegion: region,
    });
    if (identity === RESOURCE_NOT_FOUND) return RESOURCE_NOT_FOUND;
    return typeof identity === 'string' && identity !== '' ? identity : undefined;
  } catch {
    return undefined;
  }
}
