/**
 * go-to-k/cdkd#4655: whether the live resource under a journaled proven
 * orphan's physical id is still the one the failed CREATE made.
 *
 * A journaled orphan (`physicalIdRecoveredFromError`) is recorded by its
 * physical id. For a type whose physical id is a name the user chose, the
 * user can delete the orphan by hand and something cdkd does not track can
 * create another resource under the same name before the next successful
 * deploy settles the journal; deleting by that id would then delete the
 * unrelated resource. The write side journals the provider's
 * `resourceIdentity` token beside the id (`createdResourceIdentity`); the
 * success settle deletes such an orphan only when the live token still
 * matches.
 *
 * The success settle, and the `cdkd rollback` / `cdkd destroy` replay of a
 * journaled orphan (go-to-k/cdkd#4658, #4696), ask the same two questions
 * here: {@link askForeignHolder}, then {@link createdResourceStillThere}.
 *
 * A leaf at runtime: its one value import is the `RESOURCE_NOT_FOUND`
 * sentinel; `journaled-orphans.ts` and `types.ts` are imported for types
 * only, so `journaled-orphans.ts`, which imports this module at runtime,
 * forms no runtime cycle with it.
 */
import { RESOURCE_NOT_FOUND, type ResourceNotFound } from '../../types/resource.js';
import type { ProviderRegistry } from '../../provisioning/provider-registry.js';
import type { ForeignHolding } from './journaled-orphans.js';
import type { FailedOperation, RollbackExecutorContext } from './types.js';

/**
 * Types whose marked physical id is generated by AWS and never names a later
 * resource: a random id (`vpc-…`, `fs-…`, `j-…`, a KMS key UUID, an access
 * key id) or an ARN carrying a random or creation-time suffix (ELBv2, ACM,
 * a Kinesis stream consumer). A resource answering to that id IS the one the
 * failed CREATE made, so no identity is needed. Each entry was checked
 * against its provider's `markCreatedBeforeFailure` site; a type whose marked
 * id is a name, a name-built ARN or a composite of reusable keys (an API
 * Gateway stage name, a method's `restApiId|resourceId|httpMethod`) must
 * not be added.
 */
export const UNIQUE_PHYSICAL_ID_TYPES: ReadonlySet<string> = new Set([
  'AWS::EC2::VPC',
  'AWS::EC2::Subnet',
  // `publicIp|eipalloc-…`: the allocation id is never reused.
  'AWS::EC2::EIP',
  'AWS::EC2::NatGateway',
  'AWS::EC2::SecurityGroup',
  'AWS::EC2::Instance',
  'AWS::EFS::FileSystem',
  'AWS::EFS::MountTarget',
  'AWS::FSx::FileSystem',
  'AWS::KMS::Key',
  'AWS::CertificateManager::Certificate',
  'AWS::ElasticLoadBalancingV2::LoadBalancer',
  'AWS::ElasticLoadBalancingV2::TargetGroup',
  'AWS::ElasticLoadBalancingV2::Listener',
  'AWS::EMR::Cluster',
  'AWS::EMR::InstanceGroupConfig',
  'AWS::EMR::InstanceFleetConfig',
  'AWS::Cognito::UserPool',
  'AWS::Route53::HostedZone',
  'AWS::ServiceDiscovery::PrivateDnsNamespace',
  'AWS::ServiceDiscovery::PublicDnsNamespace',
  'AWS::ServiceDiscovery::HttpNamespace',
  'AWS::ServiceDiscovery::Service',
  // The marked id is the random `apiId`, not the ARN.
  'AWS::AppSync::GraphQLApi',
  'AWS::IAM::AccessKey',
  // `…/consumer/<name>:<creation epoch>`.
  'AWS::Kinesis::StreamConsumer',
]);

/**
 * Types whose orphan delete itself compares the live content with what the
 * failed CREATE wrote and clears only a match (go-to-k/cdkd#4612): the delete
 * is its own identity proof, so the settle needs no token for them.
 */
export const CONTENT_COMPARED_DELETE_TYPES: ReadonlySet<string> = new Set([
  'AWS::SQS::QueuePolicy',
  'AWS::SNS::TopicPolicy',
]);

/**
 * Types whose marked physical id lives in cdkd's own namespace, so nothing
 * outside cdkd can create a resource under it: a nested stack's
 * `arn:cdkd-local:…:nested-stack/<parent>/<logicalId>`, whose delete acts on
 * the child stack's own state record.
 */
export const CDKD_NAMESPACE_ID_TYPES: ReadonlySet<string> = new Set(['AWS::CloudFormation::Stack']);

/** Whether a proven orphan of `resourceType` needs a journaled identity before the settle deletes it. */
export function orphanDeleteNeedsIdentity(resourceType: string): boolean {
  return (
    !UNIQUE_PHYSICAL_ID_TYPES.has(resourceType) &&
    !CONTENT_COMPARED_DELETE_TYPES.has(resourceType) &&
    !CDKD_NAMESPACE_ID_TYPES.has(resourceType)
  );
}

/**
 * How long one identity read may take. No SDK client here sets a request
 * timeout, and the write side runs where a hung read would hold back the
 * journal write that is the orphan's only record.
 */
export const RESOURCE_IDENTITY_TIMEOUT_MS = 10_000;

/**
 * The provider's `resourceIdentity` for `physicalId`, asked through the
 * provider the orphan's delete would take. `RESOURCE_NOT_FOUND` when AWS
 * reports it gone; `undefined` for a provider without the method, any answer
 * that is not a non-empty string, any error (never thrown), and a read that
 * has not answered within `timeoutMs`.
 */
export async function readResourceIdentity(
  providerRegistry: Pick<ProviderRegistry, 'getProviderFor'>,
  target: {
    resourceType: string;
    physicalId: string;
    provisionedBy?: 'sdk' | 'cc-api' | undefined;
  },
  region: string,
  timeoutMs: number = RESOURCE_IDENTITY_TIMEOUT_MS
): Promise<string | ResourceNotFound | undefined> {
  let timer: ReturnType<typeof setTimeout> | undefined;
  const timedOut = new Promise<undefined>((resolve) => {
    timer = setTimeout(() => resolve(undefined), timeoutMs);
  });
  try {
    return await Promise.race([askResourceIdentity(providerRegistry, target, region), timedOut]);
  } finally {
    clearTimeout(timer);
  }
}

async function askResourceIdentity(
  providerRegistry: Pick<ProviderRegistry, 'getProviderFor'>,
  target: {
    resourceType: string;
    physicalId: string;
    provisionedBy?: 'sdk' | 'cc-api' | undefined;
  },
  region: string
): Promise<string | ResourceNotFound | undefined> {
  try {
    const { provider } = providerRegistry.getProviderFor({
      resourceType: target.resourceType,
      provisionedBy: target.provisionedBy,
    });
    if (typeof provider.resourceIdentity !== 'function') return undefined;
    const identity = await provider.resourceIdentity(target.physicalId, target.resourceType, {
      expectedRegion: region,
    });
    if (identity === RESOURCE_NOT_FOUND) return RESOURCE_NOT_FOUND;
    return typeof identity === 'string' && identity !== '' ? identity : undefined;
  } catch {
    return undefined;
  }
}

/**
 * go-to-k/cdkd#4655: whether the resource under the proven orphan `op`'s
 * physical id is still the one its failed CREATE made. `'proven'` without a
 * read for a `Retain` orphan (nothing is deleted) and for a type that needs
 * no identity (`orphanDeleteNeedsIdentity`); otherwise `'proven'` only when
 * the provider's live `resourceIdentity` equals the journaled
 * `createdResourceIdentity`, `'mismatch'` when it reads another token, and
 * `'gone'` when it reports the id gone. A legacy entry with no identity, a
 * provider without the method, and any failed read are `'unproven'`. A match
 * is read before the delete runs, not with it: no delete this check precedes
 * is conditional on an identity.
 */
export async function createdResourceStillThere(
  op: FailedOperation,
  ctx: Pick<RollbackExecutorContext, 'providerRegistry' | 'region'>
): Promise<'proven' | 'mismatch' | 'gone' | 'unproven'> {
  if (op.deletionPolicy === 'Retain') return 'proven';
  if (!orphanDeleteNeedsIdentity(op.resourceType)) return 'proven';
  // Unreachable from the settle, which skips an op without one, and from the
  // replay, whose classifier does; a guard for any other caller.
  const physicalId = op.physicalId;
  if (!physicalId) return 'unproven';
  const live = await readResourceIdentity(
    ctx.providerRegistry,
    { resourceType: op.resourceType, physicalId, provisionedBy: op.provisionedBy },
    ctx.region
  );
  if (live === RESOURCE_NOT_FOUND) return 'gone';
  const journaled = op.createdResourceIdentity;
  if (typeof journaled !== 'string' || journaled === '' || typeof live !== 'string') {
    return 'unproven';
  }
  return live === journaled ? 'proven' : 'mismatch';
}

/**
 * go-to-k/cdkd#4600 / #4696: what another stack's state record says about the
 * proven orphan `op`, asked through `foreignHolder`. A throw is an unreadable
 * answer (fail closed): the caller keeps the orphan.
 */
export async function askForeignHolder(
  foreignHolder: (resourceType: string, physicalId: string) => Promise<ForeignHolding>,
  op: Pick<FailedOperation, 'resourceType'> & { physicalId: string }
): Promise<ForeignHolding> {
  try {
    return await foreignHolder(op.resourceType, op.physicalId);
  } catch {
    return { kind: 'unreadable', what: "the other stacks' state records (the scan failed)" };
  }
}
