/**
 * Codegen: ship the provider-coverage tier-3 set into the runtime.
 *
 * Reads docs/_generated/provider-coverage.json (the cached three-tier audit
 * produced by scripts/audit-provider-coverage.ts) and writes the tier-3 list
 * — AWS CloudFormation resource types AWS reports as
 * `ProvisioningType: NON_PROVISIONABLE` (Cloud Control API cannot
 * create/update/delete them) for which cdkd has no SDK provider — into
 * src/provisioning/unsupported-types.generated.ts.
 *
 * Why a generated TS module and not a runtime JSON read: package.json `files`
 * ships only `dist`, so docs/_generated/*.json is not in the npm package. A
 * generated .ts under src/ compiles into dist and is importable at runtime.
 *
 * The pre-flight check (ProviderRegistry.validateResourceTypes via
 * CloudControlProvider.isSupportedResourceType) consults this set to fail fast
 * with an actionable message instead of letting the optimistic Cloud Control
 * fallthrough reach a mid-deploy CreateResource failure.
 *
 * Usage:
 *   node --experimental-strip-types scripts/gen-unsupported-types.ts   # write the module
 *
 * CI runs this task then `git diff --quiet` on the output (see ci.yml), so a
 * stale module (json regenerated but module not) fails the build — mirroring
 * the integ-coverage / scenario-coverage staleness guards.
 */
import { readFileSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');
const COVERAGE_JSON = resolve(repoRoot, 'docs/_generated/provider-coverage.json');
const OUT_FILE = resolve(repoRoot, 'src/provisioning/unsupported-types.generated.ts');

interface CoverageCache {
  tier3?: string[];
}

const cache = JSON.parse(readFileSync(COVERAGE_JSON, 'utf8')) as CoverageCache;
const tier3 = [...new Set(cache.tier3 ?? [])].sort((a, b) => a.localeCompare(b));

if (tier3.length === 0) {
  throw new Error(
    `No tier3 entries found in ${COVERAGE_JSON}. ` +
      `Regenerate the audit with \`vp run audit:coverage:regenerate\` first.`
  );
}

const body = tier3.map((t) => `  '${t}',`).join('\n');

const content = `/**
 * AUTO-GENERATED by scripts/gen-unsupported-types.ts — DO NOT EDIT BY HAND.
 * Source: docs/_generated/provider-coverage.json (tier3).
 * Regenerate: \`vp run gen:unsupported-types\`.
 *
 * AWS CloudFormation resource types AWS reports as
 * \`ProvisioningType: NON_PROVISIONABLE\` (Cloud Control API cannot
 * create/update/delete them) and for which cdkd has no SDK provider. cdkd
 * pre-flight rejects these fast with an actionable message instead of letting
 * the optimistic Cloud Control fallthrough fail mid-deploy.
 */
export const NON_PROVISIONABLE_TYPES: ReadonlySet<string> = new Set([
${body}
]);
`;

// Atomic write: a Ctrl-C between open and close would otherwise leave the
// generated module truncated/empty and break the next build's module load.
const tmp = `${OUT_FILE}.tmp`;
writeFileSync(tmp, content);
renameSync(tmp, OUT_FILE);
console.log(`Wrote ${tier3.length} NON_PROVISIONABLE types to ${OUT_FILE}`);
