/**
 * Codegen: ship each SDK-provider type's nested `required` lists into the
 * runtime (issue #1802).
 *
 * Reads: tests/fixtures/cfn-schemas/*.json — the `nestedRequired` section
 * written by `scripts/refresh-cfn-schemas.mjs` (`extractNestedRequired`).
 *
 * Writes: src/provisioning/nested-required.generated.ts
 *
 * The deploy pre-flight (`ProviderRegistry.validateResourceProperties` ->
 * `src/provisioning/nested-required.ts`) refuses a nested block that is
 * PRESENT but lacks a member its schema definition requires — only for the
 * types that module lists as measured to be enforced by CloudFormation. The
 * table carries every captured type; the filter lives beside the refusal.
 *
 * A generated module rather than a runtime JSON read for the reason
 * `gen-property-coverage.ts` gives: `package.json` `files` ships only `dist/`.
 *
 * Usage: node --experimental-strip-types scripts/gen-nested-required.ts
 * CI runs it through `vp run gen:all-matrices` and fails on a diff.
 */
import { readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = resolve(dirname(__filename), '..');
const FIXTURE_DIR = resolve(repoRoot, 'tests/fixtures/cfn-schemas');
const OUT_FILE = resolve(repoRoot, 'src/provisioning/nested-required.generated.ts');

interface SchemaFixture {
  resourceType?: unknown;
  nestedRequired?: Record<string, string[]>;
}

/** Collect `{ type -> { path -> required members } }`, types and paths sorted. */
export function collectNestedRequired(
  fixtures: readonly SchemaFixture[]
): Array<[string, Array<[string, string[]]>]> {
  const out: Array<[string, Array<[string, string[]]>]> = [];
  for (const fixture of fixtures) {
    if (typeof fixture.resourceType !== 'string') continue;
    const table = fixture.nestedRequired;
    if (!table || typeof table !== 'object') continue;
    const paths = Object.keys(table)
      .sort()
      .map((path): [string, string[]] => [path, [...(table[path] ?? [])].sort()])
      .filter(([, members]) => members.length > 0);
    if (paths.length > 0) out.push([fixture.resourceType, paths]);
  }
  return out.sort(([a], [b]) => a.localeCompare(b));
}

function main(): void {
  const fixtures = readdirSync(FIXTURE_DIR)
    .filter((f) => f.startsWith('AWS-') && f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(FIXTURE_DIR, f), 'utf8')) as SchemaFixture);
  const table = collectNestedRequired(fixtures);
  if (table.length === 0) {
    throw new Error(
      `No nestedRequired section found in ${FIXTURE_DIR}. ` +
        'Re-capture the fixtures with `vp run gen:cfn-schemas-from-zip` first.'
    );
  }

  const body = table
    .map(([type, paths]) => {
      const rows = paths
        .map(([path, members]) => `      [${JSON.stringify(path)}, ${JSON.stringify(members)}],`)
        .join('\n');
      return `  [\n    ${JSON.stringify(type)},\n    new Map<string, readonly string[]>([\n${rows}\n    ]),\n  ],`;
    })
    .join('\n');

  const content = `/**
 * AUTO-GENERATED by scripts/gen-nested-required.ts — DO NOT EDIT BY HAND.
 * Source: the \`nestedRequired\` section of tests/fixtures/cfn-schemas/*.json.
 * Regenerate: \`vp run gen:nested-required\`.
 *
 * Per resource type, each nested property PATH (dotted, arrays transparent)
 * mapped to the members its schema definition lists as \`required\`. What the
 * SCHEMA says, not what CloudFormation enforces: the pre-flight refusal in
 * \`nested-required.ts\` reads it only for types measured to be enforced.
 */

export const NESTED_REQUIRED: ReadonlyMap<string, ReadonlyMap<string, readonly string[]>> = new Map<
  string,
  ReadonlyMap<string, readonly string[]>
>([
${body}
]);
`;

  const tmp = `${OUT_FILE}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, OUT_FILE);
  console.log(`Wrote nested required lists for ${table.length} types to ${OUT_FILE}`);
}

const isMainModule = (): boolean => {
  if (!process.argv[1]) return false;
  return resolve(process.argv[1]) === __filename;
};

if (isMainModule()) {
  main();
}
