/**
 * Codegen: ship each SDK-provider type's per-path array / object kinds into
 * the runtime (issue #4357).
 *
 * Reads: tests/fixtures/cfn-schemas/*.json — the `propertyShapes` section
 * written by `scripts/refresh-cfn-schemas.mjs` (`extractPropertyShapes`).
 *
 * Writes: src/provisioning/property-shape.generated.ts
 *
 * The deploy pre-flight (`ProviderRegistry.validateResourceProperties` ->
 * `src/provisioning/property-shape.ts`) refuses a list where the schema wants
 * an object, or the reverse, before any provider runs.
 *
 * A generated module rather than a runtime JSON read for the reason
 * `gen-property-coverage.ts` gives: `package.json` `files` ships only `dist/`.
 *
 * Usage: node --experimental-strip-types scripts/gen-property-shape.ts
 * CI runs it through `vp run gen:all-matrices` and fails on a diff.
 */
import { readFileSync, readdirSync, renameSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const repoRoot = resolve(dirname(__filename), '..');
const FIXTURE_DIR = resolve(repoRoot, 'tests/fixtures/cfn-schemas');
const OUT_FILE = resolve(repoRoot, 'src/provisioning/property-shape.generated.ts');

interface SchemaFixture {
  resourceType?: unknown;
  propertyShapes?: Record<string, unknown>;
}

/**
 * Collect `{ type -> [path, kind][] }`, types and paths sorted. A row whose
 * kind is not `array` / `object` is dropped rather than shipped: the runtime
 * reads every row as a refusal rule.
 */
export function collectPropertyShapes(
  fixtures: readonly SchemaFixture[]
): Array<[string, Array<[string, 'array' | 'object']>]> {
  const out: Array<[string, Array<[string, 'array' | 'object']>]> = [];
  for (const fixture of fixtures) {
    if (typeof fixture.resourceType !== 'string') continue;
    const table = fixture.propertyShapes;
    if (!table || typeof table !== 'object') continue;
    const rows = Object.keys(table)
      .sort()
      .flatMap((path): Array<[string, 'array' | 'object']> => {
        const kind = table[path];
        return kind === 'array' || kind === 'object' ? [[path, kind]] : [];
      });
    if (rows.length > 0) out.push([fixture.resourceType, rows]);
  }
  return out.sort(([a], [b]) => a.localeCompare(b));
}

function main(): void {
  const fixtures = readdirSync(FIXTURE_DIR)
    .filter((f) => f.startsWith('AWS-') && f.endsWith('.json'))
    .sort()
    .map((f) => JSON.parse(readFileSync(join(FIXTURE_DIR, f), 'utf8')) as SchemaFixture);
  const table = collectPropertyShapes(fixtures);
  if (table.length === 0) {
    throw new Error(
      `No propertyShapes section found in ${FIXTURE_DIR}. ` +
        'Re-capture the fixtures with `vp run gen:cfn-schemas-from-zip` first.'
    );
  }

  const body = table
    .map(([type, rows]) => {
      const lines = rows
        .map(([path, kind]) => `    ${JSON.stringify(path)}: ${JSON.stringify(kind)},`)
        .join('\n');
      return `  [\n    ${JSON.stringify(type)},\n    {\n${lines}\n    },\n  ],`;
    })
    .join('\n');

  const content = `/**
 * AUTO-GENERATED by scripts/gen-property-shape.ts — DO NOT EDIT BY HAND.
 * Source: the \`propertyShapes\` section of tests/fixtures/cfn-schemas/*.json.
 * Regenerate: \`vp run gen:property-shape\`.
 *
 * Per resource type, each property PATH (dotted; \`[]\` marks an array's
 * elements) mapped to the JSON kind its schema requires there. Only paths whose
 * schema admits exactly one of \`array\` / \`object\` are listed; the pre-flight
 * refusal in \`property-shape.ts\` reads them.
 */

export const PROPERTY_SHAPES: ReadonlyMap<
  string,
  Readonly<Record<string, 'array' | 'object'>>
> = new Map<string, Readonly<Record<string, 'array' | 'object'>>>([
${body}
]);
`;

  const tmp = `${OUT_FILE}.tmp`;
  writeFileSync(tmp, content);
  renameSync(tmp, OUT_FILE);
  console.log(`Wrote property shapes for ${table.length} types to ${OUT_FILE}`);
}

const isMainModule = (): boolean => {
  if (!process.argv[1]) return false;
  return resolve(process.argv[1]) === __filename;
};

if (isMainModule()) {
  main();
}
