import { Command } from 'commander';
import { lstatSync, writeFileSync } from 'node:fs';
import {
  annotationMessageOptions,
  appOptions,
  commonOptions,
  contextOptions,
  deprecatedRegionOption,
  parseContextOptions,
  warnIfDeprecatedRegion,
} from '../options.js';
import { getLogger, reserveStdoutForPayload } from '../../utils/logger.js';
import { describeStack, matchStacks, renderNoStackMatch } from '../stack-matcher.js';
import { bold, green } from '../../utils/colors.js';
import { applyRoleArnIfSet } from '../../utils/role-arn.js';
import { foldRegionOption } from '../region-options.js';
import { SynthesisError, withErrorHandling } from '../../utils/error-handler.js';
import {
  Synthesizer,
  synthesisStatusMessage,
  type SynthesisOptions,
} from '../../synthesis/synthesizer.js';
import { AssemblyReader } from '../../synthesis/assembly-reader.js';
import { processStackMessages } from '../../synthesis/stack-messages.js';
import { resolveApp } from '../config-loader.js';
import { toYaml } from '../../utils/yaml.js';
import { displaySafe, displayStackName } from '../../utils/display-safe.js';
import {
  displayAssemblyPath,
  renderAssemblyPathEscape,
  resolveAssemblyPath,
} from '../../utils/assembly-path.js';
import type { CloudFormationTemplate } from '../../types/resource.js';

/**
 * Count deployable resources in a synth template.
 *
 * Excludes `AWS::CDK::Metadata` (CDK-injected construct-tree marker; cdkd deploy
 * also filters this out, so the two commands stay in sync — see
 * deploy-engine.ts `validateResourceTypes` call site).
 */
export function countDeployableResources(template: CloudFormationTemplate): number {
  return Object.values(template.Resources ?? {}).filter((r) => r.Type !== 'AWS::CDK::Metadata')
    .length;
}

/**
 * Where `cdkd synth --verbose` writes one stack's template, refusing a path
 * that leaves `outputDir` (issue
 * [#3489](https://github.com/go-to-k/cdkd/issues/3489)).
 *
 * `stackName` is the assembly manifest's own `properties.stackName`, falling
 * back to the artifact id, so it is chosen by whoever wrote the assembly — and
 * this is the ONE place cdkd turns such a string into a path it WRITES. A
 * `../../../..`-bearing name would put attacker-chosen JSON outside the output
 * directory, clobbering whatever `<name>.template.json` it can reach.
 *
 * Exported for unit testing.
 */
export function resolveVerboseTemplatePath(outputDir: string, stackName: string): string {
  const resolved = resolveAssemblyPath(outputDir, `${stackName}.template.json`);
  if (!resolved.contained) {
    throw new SynthesisError(
      `Stack ${displayStackName(stackName)} would write its template to a path that ` +
        `${renderAssemblyPathEscape(resolved, outputDir, 'write it')}`
    );
  }

  // Then ask the KERNEL, because this is the only site that creates a file.
  //
  // `resolveAssemblyPath` is exact for a path that fully resolves and a MODEL
  // for one that does not (its doc comment names the `..`-inside-a-link-target
  // edge). A write is always in the second case — the file does not exist yet
  // — and `writeFileSync` FOLLOWS a symbolic link, so every refinement of that
  // model is one more shape to be argued around. `lstat` ends the argument:
  // it does not follow the link, so a symbolic link here is refused whatever
  // it points at, dangling or not. A CDK assembly has none at this path, and a
  // re-run over a regular file is unaffected.
  let linked = false;
  try {
    linked = lstatSync(resolved.path).isSymbolicLink();
  } catch {
    // Nothing there yet: the ordinary case for a file about to be created.
  }
  if (linked) {
    throw new SynthesisError(
      `Stack ${displayStackName(stackName)} would write its template over a symbolic link at ` +
        `${displayAssemblyPath(resolved.path)}. cdkd writes a stack's template as a regular file ` +
        `beside the assembly; a symbolic link there redirects the write to wherever it ` +
        `points, so this indicates the synth output was hand-modified or generated by a ` +
        `non-CDK toolchain. Refusing to write it.`
    );
  }

  return resolved.path;
}

/**
 * Synth command implementation.
 *
 * Exported for the wiring test that pins `--verbose` writing through
 * {@link resolveVerboseTemplatePath} rather than a bare `path.join`
 * (go-to-k/cdkd#3489): the guard has its own cases, but reverting the CALL
 * SITE left the suite green.
 */
export async function synthCommand(
  stackPatterns: string[],
  options: {
    app?: string;
    output: string;
    verbose: boolean;
    region?: string;
    profile?: string;
    roleArn?: string;
    context?: string[];
    strict?: boolean;
    ignoreErrors?: boolean;
  }
): Promise<void> {
  const logger = getLogger();

  if (options.verbose) {
    logger.setLevel('debug');
  }

  // Issue #2410: on `cdkd synth`, stdout MEANS "the CloudFormation template"
  // and nothing else — matching `cdk synth`, which prints only the template
  // there and routes every log line to stderr. Unlike the issue-#2280 sites
  // this reservation is UNCONDITIONAL: the payload has no `--json` flag to
  // key off, so the default output contract itself moves. Claimed before the
  // `Synthesizing CDK app...` line below and before synthesis runs at all —
  // `app-executor.ts` re-emits the CDK app's stderr (bundling progress,
  // warnings) at INFO, so a DEFAULT run put prose inside the document with no
  // `--verbose` involved. This was necessary but not sufficient for
  // `cdkd synth | yq`: the stream was clean while the DOCUMENT on it was
  // still invalid, because `toYaml` left YAML indicator characters unquoted
  // and a template containing `"*"` emitted a bare `- *` a parser rejects.
  // That half is fixed too, in
  // [#2421](https://github.com/go-to-k/cdkd/issues/2421) — `toYaml` now
  // delegates its quoting to the `yaml` package, so the two halves together
  // are what make the pipe work.
  //
  // Accepted consequence, stated because it is a real behavior change rather
  // than an oversight: in the MULTI-stack case nothing at all is written to
  // stdout (the template is emitted only for a single stack, below) and the
  // whole `Synthesis complete!` summary block goes to stderr. stdout on
  // `synth` is the template or it is empty; the summary is never a payload.
  // Lines are MOVED, not suppressed — a terminal shows exactly what it did
  // before, and `2>&1` restores the old single-stream view.
  reserveStdoutForPayload();

  // PR 5: --region is deprecated on non-bootstrap commands. Warn but keep
  // the rest of the pipeline working as before.
  warnIfDeprecatedRegion(options);

  // Resolve --role-arn / CDKD_ROLE_ARN before any AWS call.
  // Issue #2065 - fold `--region` ONCE, at the boundary, so no raw spelling
  // reaches an SDK client, an ARN segment or a state key. Rationale (and why
  // this is per-command rather than per-consumer) in `src/cli/region-options.ts`.
  foldRegionOption(options);
  await applyRoleArnIfSet({ roleArn: options.roleArn, region: options.region });

  // Resolve --app from CLI, env, or cdk.json
  const app = resolveApp(options.app);
  if (!app) {
    throw new Error(
      'No app command specified. Use --app, set CDKD_APP env var, or add "app" to cdk.json'
    );
  }
  options.app = app;

  logger.info(synthesisStatusMessage(app, 'Synthesizing CDK app...'));
  logger.debug('App command:', options.app);
  logger.debug('Output directory:', options.output);

  // Create synthesizer
  const synthesizer = new Synthesizer();
  const assemblyReader = new AssemblyReader();

  // Synthesize CDK app
  const context = parseContextOptions(options.context);
  const synthOptions: SynthesisOptions = {
    app: options.app,
    output: options.output,
    ...(options.region && { region: options.region }),
    ...(options.profile && { profile: options.profile }),
    ...(Object.keys(context).length > 0 && { context }),
  };

  const result = await synthesizer.synthesize(synthOptions);
  const { stacks: allStacks, assemblyDir } = result;

  // SELECTION HAPPENS AFTER SYNTHESIS, NEVER BEFORE, and that is upstream's
  // shape rather than a convenience (issue
  // [#3550](https://github.com/go-to-k/cdkd/issues/3550)). Measured in
  // `aws-cdk@2.1142.0`: `Toolkit.synth` calls `synthAndMeasure(...)` and only
  // then `assembly.selectStacks(...)`, and the context-resolution loop in
  // `cxapp/cloud-executable.ts` takes no selector at all — it reads
  // `assembly.manifest.missing` for the WHOLE assembly. So a stack argument
  // does NOT narrow which `cdk.context.json` lookups run, and narrowing
  // synthesis here would diverge from `cdk` in a way nothing would report.
  const selected = stackPatterns.length > 0 ? matchStacks(allStacks, stackPatterns) : allStacks;
  if (selected.length === 0) {
    throw new Error(renderNoStackMatch(stackPatterns, allStacks, result));
  }
  const stacks = selected;

  // CDK CLI parity (issue #1228): surface Annotations messages — print
  // warnings/infos, refuse to emit a template when any stack carries an
  // error annotation (`cdk synth` fails with "Found errors" too).
  // #1230: `--strict` also fails on warnings; `--ignore-errors` never fails.
  processStackMessages(stacks, logger, {
    strict: options.strict === true,
    ignoreErrors: options.ignoreErrors === true,
  });

  // Print the template to stdout when the SELECTION is one stack — not when
  // the assembly happens to hold one. That distinction is the whole of
  // go-to-k/cdkd#3550: the gate used to read `allStacks.length === 1`, so on a
  // multi-stack app there was NO way to get a single template onto stdout,
  // and the selector that would have narrowed it was refused as an excess
  // argument. `cdk synth MyStack` prints exactly this.
  if (stacks.length === 1) {
    const template = stacks[0]!.template;
    process.stdout.write(toYaml(template));
  } else {
    // Whenever the SELECTION is not exactly one, and listing the SELECTED
    // ids rather than every id in the assembly. Both halves are upstream's,
    // and both were wrong in the first draft of this: it gated the hint on
    // "no pattern was given", so `cdkd synth 'My*'` matching three stacks
    // printed neither a template nor a way to get one, and it listed the
    // whole assembly, which is the wrong set to narrow from.
    // `describeStack`, not a raw `stackName`: this prints on a NORMAL run, and
    // `.claude/rules/layout-synthesis.md` requires an identifier in cdkd prose
    // go through the display helper. It also renders the DISPLAY PATH, which
    // is what upstream's own `Supply a stack id` lists and what the user has
    // to type back.
    logger.info(
      `Supply a stack id (${stacks.map(describeStack).join(', ')}) to display its template.`
    );
  }

  // Count the SELECTION against the assembly when a pattern narrowed it.
  // `Found 1 stack(s)` on a three-stack app is false: every stack was
  // synthesized, only one is being reported on.
  const found =
    stacks.length === allStacks.length
      ? `Found ${stacks.length} stack(s):`
      : `Found ${stacks.length} of ${allStacks.length} stack(s):`;
  logger.info(`\n${green('✓')} ${bold('Synthesis complete!')} ${found}`);

  for (const stack of stacks) {
    const resourceCount = countDeployableResources(stack.template);
    const outputCount = Object.keys(stack.template.Outputs ?? {}).length;

    logger.info(`  • ${stack.stackName}`);
    logger.info(`    - Resources: ${resourceCount}`);
    logger.info(`    - Outputs: ${outputCount}`);
    logger.info(`    - Has assets: ${assemblyReader.hasAssets(stack) ? 'Yes' : 'No'}`);

    if (options.verbose) {
      const templatePath = resolveVerboseTemplatePath(options.output, stack.stackName);
      writeFileSync(templatePath, JSON.stringify(stack.template, null, 2));
      logger.debug(`    - Template written to: ${displaySafe(templatePath)}`);
    }
  }

  logger.info(`\nOutput: ${assemblyDir}`);
}

/**
 * Create synth command
 */
export function createSynthCommand(): Command {
  const cmd = new Command('synth')
    .description('Synthesize CDK app to CloudFormation template')
    .argument(
      '[stacks...]',
      "Stack name(s) whose template to print. Accepts physical CloudFormation names (e.g. 'MyStage-Api') or CDK display paths (e.g. 'MyStage/Api'). Supports wildcards (e.g. 'MyStage/*'). Every stack is synthesized either way -- the selection decides what reaches stdout."
    )
    .action(withErrorHandling(synthCommand));

  // Add options
  [...commonOptions, ...appOptions, ...contextOptions, ...annotationMessageOptions].forEach((opt) =>
    cmd.addOption(opt)
  );

  // --region is deprecated for synth (PR 5). Accepted for backward
  // compatibility; warning emitted at runtime via warnIfDeprecatedRegion.
  cmd.addOption(deprecatedRegionOption);

  return cmd;
}
