import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as iam from 'aws-cdk-lib/aws-iam';

/**
 * RDS Aurora Serverless v2 example stack
 *
 * Demonstrates:
 * - VPC creation (1 AZ, no NAT gateways for cost savings)
 * - Aurora Serverless v2 cluster (MySQL) via the L2 `rds.DatabaseCluster`
 *   + writer instance + DBProxy / DBProxyEndpoint family.
 * - Security Group for RDS access
 * - Secrets Manager secret for credentials (auto-generated by CDK)
 * - CfnOutputs for cluster endpoint, secret ARN, VPC ID
 * - Multiple resource types and dependencies
 *
 * Folded-in #609 DBCluster security backfill (this fixture absorbs the
 * DBCluster half of the former standalone `rds-security-backfill` fixture
 * per the "do not proliferate per-property integ fixtures" directive):
 *
 * A SECOND, standalone L1 `rds.CfnDBCluster` ("SecurityCluster") is added
 * alongside the L2 cluster above to exercise the #609 silent-drop backfill
 * of the DBCluster security props:
 *   ManageMasterUserPassword / MasterUserSecret / EnableIAMDatabaseAuthentication
 *
 * Why a separate L1 cluster instead of folding onto the existing L2 one:
 * the L2 `rds.DatabaseCluster` emits CDK-default top-level props (some still
 * in the #609 silent-drop list) and per cdkd's #614 routing rule even one
 * silent-dropped prop flips the whole resource off the SDK provider onto
 * Cloud Control — which would defeat the `provisionedBy=sdk` routing guard
 * the security verify relies on. The L1 lets us assert exactly which CFn
 * props reach AWS and keep `provisionedBy=sdk`. It is an Aurora Serverless
 * v2 cluster with NO cluster instance (cluster-level create validates and
 * reflects every security prop without paying for a provisioned instance).
 * KMS keys are account-default AWS-managed aliases (no CMK created), and
 * Enhanced Monitoring uses a dedicated IAM role.
 */
export class RdsAuroraStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    // Create VPC with 2 AZs (Aurora requires at least 2 subnets) and no NAT gateways
    const vpc = new ec2.Vpc(this, 'AuroraVpc', {
      maxAzs: 2,
      natGateways: 0,
      subnetConfiguration: [
        {
          cidrMask: 24,
          name: 'Isolated',
          subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
        },
      ],
    });

    // Create Security Group for Aurora cluster
    const securityGroup = new ec2.SecurityGroup(this, 'AuroraSecurityGroup', {
      vpc,
      description: 'Security group for Aurora Serverless v2 cluster',
      allowAllOutbound: true,
    });

    // Allow MySQL port from within the VPC (using VPC CIDR is not supported yet, use security group self-reference)
    securityGroup.addIngressRule(
      securityGroup,
      ec2.Port.tcp(3306),
      'Allow MySQL access from within security group'
    );

    // Create Aurora Serverless v2 cluster (MySQL)
    // CDK automatically creates a Secrets Manager secret for credentials
    const cluster = new rds.DatabaseCluster(this, 'AuroraCluster', {
      engine: rds.DatabaseClusterEngine.auroraMysql({
        version: rds.AuroraMysqlEngineVersion.VER_3_08_0,
      }),
      serverlessV2MinCapacity: 0.5,
      serverlessV2MaxCapacity: 1,
      writer: rds.ClusterInstance.serverlessV2('Writer', {
        publiclyAccessible: false,
      }),
      vpc,
      vpcSubnets: {
        subnetType: ec2.SubnetType.PRIVATE_ISOLATED,
      },
      securityGroups: [securityGroup],
      defaultDatabaseName: 'appdb',
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    // Create RDS Proxy for the Aurora cluster
    const proxy = new rds.DatabaseProxy(this, 'AuroraProxy', {
      proxyTarget: rds.ProxyTarget.fromCluster(cluster),
      secrets: [cluster.secret!],
      vpc,
      securityGroups: [securityGroup],
      requireTLS: false,
    });

    // Add a READ_ONLY DBProxyEndpoint to exercise the
    // AWS::RDS::DBProxyEndpoint SDK provider end-to-end. Reuses the
    // cluster's VPC subnets + security group.
    proxy.addEndpoint('ReaderEndpoint', {
      dbProxyEndpointName: `${cdk.Stack.of(this).stackName.toLowerCase()}-reader`,
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      securityGroups: [securityGroup],
      targetRole: rds.ProxyEndpointTargetRole.READ_ONLY,
    });

    // --- #609 DBCluster security backfill: standalone L1 CfnDBCluster ----
    // A DBSubnetGroup spanning >= 2 AZs for the security cluster. The
    // subnet-group code path has its own dedicated SDK provider and is
    // unaffected by the DBCluster routing concern, so the L2 helper is fine.
    const securitySubnetGroup = new rds.SubnetGroup(this, 'SecuritySubnetGroup', {
      vpc,
      vpcSubnets: { subnetType: ec2.SubnetType.PRIVATE_ISOLATED },
      description: 'Subnet group for the #609 security-backfill DBCluster',
    });

    // Enhanced Monitoring role: RDS assumes monitoring.rds.amazonaws.com and
    // needs the AWS-managed AmazonRDSEnhancedMonitoringRole policy.
    const monitoringRole = new iam.Role(this, 'SecurityMonitoringRole', {
      assumedBy: new iam.ServicePrincipal('monitoring.rds.amazonaws.com'),
      managedPolicies: [
        iam.ManagedPolicy.fromAwsManagedPolicyName('service-role/AmazonRDSEnhancedMonitoringRole'),
      ],
    });

    // Aurora PostgreSQL Serverless v2 cluster — NO cluster instance: the
    // cluster-level create accepts and reflects every security prop, and
    // skipping the instance keeps the fixture cheap. Each #609 security prop
    // is set explicitly so verify.sh can prove it reached AWS:
    //   * ManageMasterUserPassword: Secrets-Manager-managed master password,
    //     mutually exclusive with MasterUserPassword (none is set).
    //   * MasterUserSecret { KmsKeyId } → account-default Secrets Manager key.
    //   * EnableIAMDatabaseAuthentication: true (AWS default false).
    //   * MonitoringInterval: 60 (AWS default 0) + MonitoringRoleArn.
    //
    // MonitoringRoleArn references a same-stack IAM role. cdkd's fast SDK path
    // issues CreateDBCluster before IAM finishes propagating that just-created
    // role for the RDS monitoring service ("IAM role ARN value is invalid or
    // does not include the required permissions for: ENHANCED_MONITORING").
    // Issue #794 makes the deploy engine retry CreateDBCluster on that signal
    // (the new retryable-errors pattern), so the cluster create recovers once
    // IAM propagates — this fixture is the real-AWS proof of that fix.
    //
    // NOTE: PubliclyAccessible is intentionally NOT set here. It is a valid
    // CreateDBCluster field ONLY for Multi-AZ DB clusters (provisioned,
    // non-Aurora engines); AWS rejects it for aurora-postgresql with
    // "PubliclyAccessible isn't supported for DB engine aurora-postgresql"
    // (even for `false`). The provider wiring is correct (it forwards the
    // field; AWS validates per-engine) and is unit-tested; a real-AWS integ
    // assertion would need a Multi-AZ DB cluster fixture (3 instances, slow) —
    // deferred. So PubliclyAccessible stays unit-test-only.
    new rds.CfnDBCluster(this, 'SecurityCluster', {
      engine: 'aurora-postgresql',
      masterUsername: 'postgres',
      manageMasterUserPassword: true,
      masterUserSecret: { kmsKeyId: 'alias/aws/secretsmanager' },
      enableIamDatabaseAuthentication: true,
      monitoringInterval: 60,
      monitoringRoleArn: monitoringRole.roleArn,
      dbSubnetGroupName: securitySubnetGroup.subnetGroupName,
      vpcSecurityGroupIds: [securityGroup.securityGroupId],
      serverlessV2ScalingConfiguration: {
        minCapacity: 0.5,
        maxCapacity: 1,
      },
    });

    // Outputs
    new cdk.CfnOutput(this, 'ProxyEndpoint', {
      value: proxy.endpoint,
      description: 'RDS Proxy endpoint',
    });

    new cdk.CfnOutput(this, 'ClusterEndpoint', {
      value: cluster.clusterEndpoint.hostname,
      description: 'Aurora cluster endpoint',
    });

    new cdk.CfnOutput(this, 'SecretArn', {
      value: cluster.secret?.secretArn ?? 'N/A',
      description: 'Secrets Manager secret ARN for database credentials',
    });

    new cdk.CfnOutput(this, 'VpcId', {
      value: vpc.vpcId,
      description: 'VPC ID',
    });
  }
}
